import 'package:fhir_r4/fhir_r4.dart';

/// The type of relationship between documents.
enum DocumentRelationshipType {
  /// Display: Replaces
  /// Definition: This document logically replaces or supersedes the target document.
  replaces('replaces'),

  /// Display: Transforms
  /// Definition: This document was generated by transforming the target document (e.g. format or language conversion).
  transforms('transforms'),

  /// Display: Signs
  /// Definition: This document is a signature of the target document.
  signs('signs'),

  /// Display: Appends
  /// Definition: This document adds additional information to the target document.
  appends('appends'),
  elementOnly('', null),
  ;

  final String fhirCode;
  final Element? element;

  const DocumentRelationshipType(this.fhirCode, [this.element]);

  Map<String, dynamic> toJson() => {
        'value': fhirCode.isEmpty ? null : fhirCode,
        if (element != null) '_value': element!.toJson(),
      };

  static DocumentRelationshipType fromJson(Map<String, dynamic> json) {
    final String? value = json['value'] as String?;
    final Map<String, dynamic>? elementJson =
        json['_value'] as Map<String, dynamic>?;
    final Element? element =
        elementJson != null ? Element.fromJson(elementJson) : null;
    if (value == null && element != null) {
      return DocumentRelationshipType.elementOnly.withElement(element);
    }
    return DocumentRelationshipType.values.firstWhere(
      (e) => e.fhirCode == value,
    );
  }

  DocumentRelationshipType withElement(Element? newElement) {
    return DocumentRelationshipType.fromJson({
      'value': fhirCode,
      '_value': newElement?.toJson(),
    });
  }
}
