// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars, unused_element, flutter_style_todos

import 'package:fhir_r4/fhir_r4.dart';

/// The type of relationship between documents.
enum DocumentRelationshipType {
  /// Display: Replaces
  /// Definition: This document logically replaces or supersedes the target document.
  replaces('replaces'),

  /// Display: Transforms
  /// Definition: This document was generated by transforming the target document (e.g. format or language conversion).
  transforms('transforms'),

  /// Display: Signs
  /// Definition: This document is a signature of the target document.
  signs('signs'),

  /// Display: Appends
  /// Definition: This document adds additional information to the target document.
  appends('appends'),

  /// For instances where an Element is present but not value

  elementOnly(''),
  ;

  const DocumentRelationshipType(this.fhirCode, [this.element]);

  /// The String value of this enum
  final String fhirCode;

  /// The Element value of this enum
  final Element? element;

  /// Serializes the instance to JSON with standardized keys
  Map<String, dynamic> toJson() => {
        'value': fhirCode.isEmpty ? null : fhirCode,
        if (element != null) '_value': element!.toJson(),
      };

  /// Converts a list of JSON values to a list of [DocumentRelationshipType] instances.
  static DocumentRelationshipType fromJson(
    Map<String, dynamic> json,
  ) {
    final value = json['value'] as String?;
    final elementJson = json['_value'] as Map<String, dynamic>?;
    final element = elementJson != null ? Element.fromJson(elementJson) : null;
    if (value == null && element != null) {
      return DocumentRelationshipType.elementOnly.withElement(
        element,
      );
    }
    return DocumentRelationshipType.values.firstWhere(
      (e) => e.fhirCode == value,
    );
  }

  /// Returns the enum value with an element
  DocumentRelationshipType withElement(Element? newElement) {
    return DocumentRelationshipType.fromJson({
      'value': fhirCode,
      '_value': newElement?.toJson(),
    });
  }
}
