// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars, unused_element, flutter_style_todos

import 'package:fhir_r4/fhir_r4.dart';

/// A code that indicates how the page is generated.
enum GuidePageGeneration {
  /// Display: HTML
  /// Definition: Page is proper xhtml with no templating. Will be brought across unchanged for standard post-processing.
  html('html'),

  /// Display: Markdown
  /// Definition: Page is markdown with templating. Will use the template to create a file that imports the markdown file prior to post-processing.
  markdown('markdown'),

  /// Display: XML
  /// Definition: Page is xml with templating. Will use the template to create a file that imports the source file and run the nominated XSLT transform (see parameters) if present prior to post-processing.
  xml('xml'),

  /// Display: Generated
  /// Definition: Page will be generated by the publication process - no source to bring across.
  generated('generated'),

  /// For instances where an Element is present but not value

  elementOnly(''),
  ;

  const GuidePageGeneration(this.fhirCode, [this.element]);

  /// The String value of this enum
  final String fhirCode;

  /// The Element value of this enum
  final Element? element;

  /// Serializes the instance to JSON with standardized keys
  Map<String, dynamic> toJson() => {
        'value': fhirCode.isEmpty ? null : fhirCode,
        if (element != null) '_value': element!.toJson(),
      };

  /// Converts a list of JSON values to a list of [GuidePageGeneration] instances.
  static GuidePageGeneration fromJson(
    Map<String, dynamic> json,
  ) {
    final value = json['value'] as String?;
    final elementJson = json['_value'] as Map<String, dynamic>?;
    final element = elementJson != null ? Element.fromJson(elementJson) : null;
    if (value == null && element != null) {
      return GuidePageGeneration.elementOnly.withElement(
        element,
      );
    }
    return GuidePageGeneration.values.firstWhere(
      (e) => e.fhirCode == value,
    );
  }

  /// Returns the enum value with an element
  GuidePageGeneration withElement(Element? newElement) {
    return GuidePageGeneration.fromJson({
      'value': fhirCode,
      '_value': newElement?.toJson(),
    });
  }
}
