import 'package:json_annotation/json_annotation.dart';

/// The Digital Signature Purposes, an indication of the reason an entity signs a document. This is included in the signed information and can be used when determining accountability for various actions concerning the document. Examples include: author, transcriptionist/recorder, and witness.
enum SignatureTypeCodes {
  /// Display: Author's Signature
  /// Definition: the signature of the primary or sole author of a health information document. There can be only one primary author of a health information document.
  @JsonValue('1.2.840.10065.1.12.1.1')
  value1_2_840_10065_1_12_1_1,

  /// Display: Coauthor's Signature
  /// Definition: the signature of a health information document coauthor. There can be multiple coauthors of a health information document.
  @JsonValue('1.2.840.10065.1.12.1.2')
  value1_2_840_10065_1_12_1_2,

  /// Display: Co-participant's Signature
  /// Definition: the signature of an individual who is a participant in the health information document but is not an author or coauthor. (Example a surgeon who is required by institutional, regulatory, or legal rules to sign an operative report, but who was not involved in the authorship of that report.)
  @JsonValue('1.2.840.10065.1.12.1.3')
  value1_2_840_10065_1_12_1_3,

  /// Display: Transcriptionist/Recorder Signature
  /// Definition: the signature of an individual who has transcribed a dictated document or recorded written text into a digital machine readable format.
  @JsonValue('1.2.840.10065.1.12.1.4')
  value1_2_840_10065_1_12_1_4,

  /// Display: Verification Signature
  /// Definition: a signature verifying the information contained in a document. (Example a physician is required to countersign a verbal order that has previously been recorded in the medical record by a registered nurse who has carried out the verbal order.)
  @JsonValue('1.2.840.10065.1.12.1.5')
  value1_2_840_10065_1_12_1_5,

  /// Display: Validation Signature
  /// Definition: a signature validating a health information document for inclusion in the patient record. (Example a medical student or resident is credentialed to perform history or physical examinations and to write progress notes. The attending physician signs the history and physical examination to validate the entry for inclusion in the patient's medical record.)
  @JsonValue('1.2.840.10065.1.12.1.6')
  value1_2_840_10065_1_12_1_6,

  /// Display: Consent Signature
  /// Definition: the signature of an individual consenting to what is described in a health information document.
  @JsonValue('1.2.840.10065.1.12.1.7')
  value1_2_840_10065_1_12_1_7,

  /// Display: Signature Witness Signature
  /// Definition: the signature of a witness to any other signature.
  @JsonValue('1.2.840.10065.1.12.1.8')
  value1_2_840_10065_1_12_1_8,

  /// Display: Event Witness Signature
  /// Definition: the signature of a witness to an event. (Example the witness has observed a procedure and is attesting to this fact.)
  @JsonValue('1.2.840.10065.1.12.1.9')
  value1_2_840_10065_1_12_1_9,

  /// Display: Identity Witness Signature
  /// Definition: the signature of an individual who has witnessed another individual who is known to them signing a document. (Example the identity witness is a notary public.)
  @JsonValue('1.2.840.10065.1.12.1.10')
  value1_2_840_10065_1_12_1_10,

  /// Display: Consent Witness Signature
  /// Definition: the signature of an individual who has witnessed the health care provider counselling a patient.
  @JsonValue('1.2.840.10065.1.12.1.11')
  value1_2_840_10065_1_12_1_11,

  /// Display: Interpreter Signature
  /// Definition: the signature of an individual who has translated health care information during an event or the obtaining of consent to a treatment.
  @JsonValue('1.2.840.10065.1.12.1.12')
  value1_2_840_10065_1_12_1_12,

  /// Display: Review Signature
  /// Definition: the signature of a person, device, or algorithm that has reviewed or filtered data for inclusion into the patient record. ( Examples: (1) a medical records clerk who scans a document for inclusion in the medical record, enters header information, or catalogues and classifies the data, or a combination thereof; (2) a gateway that receives data from another computer system and interprets that data or changes its format, or both, before entering it into the patient record.)
  @JsonValue('1.2.840.10065.1.12.1.13')
  value1_2_840_10065_1_12_1_13,

  /// Display: Source Signature
  /// Definition: the signature of an automated data source. (Examples: (1) the signature for an image that is generated by a device for inclusion in the patient record; (2) the signature for an ECG derived by an ECG system for inclusion in the patient record; (3) the data from a biomedical monitoring device or system that is for inclusion in the patient record.)
  @JsonValue('1.2.840.10065.1.12.1.14')
  value1_2_840_10065_1_12_1_14,

  /// Display: Addendum Signature
  /// Definition: the signature on a new amended document of an individual who has corrected, edited, or amended an original health information document. An addendum signature can either be a signature type or a signature sub-type (see 8.1). Any document with an addendum signature shall have a companion document that is the original document with its original, unaltered content, and original signatures. The original document shall be referenced via an attribute in the new document, which contains, for example, the digest of the old document. Whether the original, unaltered, document is always displayed with the addended document is a local matter, but the original, unaltered, document must remain as part of the patient record and be retrievable on demand.
  @JsonValue('1.2.840.10065.1.12.1.15')
  value1_2_840_10065_1_12_1_15,

  /// Display: Modification Signature
  /// Definition: the signature on an original document of an individual who has generated a new amended document. This (original) document shall reference the new document via an additional signature purpose. This is the inverse of an addendum signature and provides a pointer from the original to the amended document.
  @JsonValue('1.2.840.10065.1.12.1.16')
  value1_2_840_10065_1_12_1_16,

  /// Display: Administrative (Error/Edit) Signature
  /// Definition: the signature of an individual who is certifying that the document is invalidated by an error(s), or is placed in the wrong chart. An administrative (error/edit) signature must include an addendum to the document and therefore shall have an addendum signature sub-type (see 8.1). This signature is reserved for the highest health information system administrative classification, since it is a statement that the entire document is invalidated by the error and that the document should no longer be used for patient care, although for legal reasons the document must remain part of the permanent patient record.
  @JsonValue('1.2.840.10065.1.12.1.17')
  value1_2_840_10065_1_12_1_17,

  /// Display: Timestamp Signature
  /// Definition: the signature by an entity or device trusted to provide accurate timestamps. This timestamp might be provided, for example, in the signature time attribute.
  @JsonValue('1.2.840.10065.1.12.1.18')
  value1_2_840_10065_1_12_1_18,
  ;

  @override
  String toString() {
    switch (this) {
      case value1_2_840_10065_1_12_1_1:
        return '1.2.840.10065.1.12.1.1';
      case value1_2_840_10065_1_12_1_2:
        return '1.2.840.10065.1.12.1.2';
      case value1_2_840_10065_1_12_1_3:
        return '1.2.840.10065.1.12.1.3';
      case value1_2_840_10065_1_12_1_4:
        return '1.2.840.10065.1.12.1.4';
      case value1_2_840_10065_1_12_1_5:
        return '1.2.840.10065.1.12.1.5';
      case value1_2_840_10065_1_12_1_6:
        return '1.2.840.10065.1.12.1.6';
      case value1_2_840_10065_1_12_1_7:
        return '1.2.840.10065.1.12.1.7';
      case value1_2_840_10065_1_12_1_8:
        return '1.2.840.10065.1.12.1.8';
      case value1_2_840_10065_1_12_1_9:
        return '1.2.840.10065.1.12.1.9';
      case value1_2_840_10065_1_12_1_10:
        return '1.2.840.10065.1.12.1.10';
      case value1_2_840_10065_1_12_1_11:
        return '1.2.840.10065.1.12.1.11';
      case value1_2_840_10065_1_12_1_12:
        return '1.2.840.10065.1.12.1.12';
      case value1_2_840_10065_1_12_1_13:
        return '1.2.840.10065.1.12.1.13';
      case value1_2_840_10065_1_12_1_14:
        return '1.2.840.10065.1.12.1.14';
      case value1_2_840_10065_1_12_1_15:
        return '1.2.840.10065.1.12.1.15';
      case value1_2_840_10065_1_12_1_16:
        return '1.2.840.10065.1.12.1.16';
      case value1_2_840_10065_1_12_1_17:
        return '1.2.840.10065.1.12.1.17';
      case value1_2_840_10065_1_12_1_18:
        return '1.2.840.10065.1.12.1.18';
    }
  }

  String toJson() => toString();
  SignatureTypeCodes fromString(String str) {
    switch (str) {
      case '1.2.840.10065.1.12.1.1':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_1;
      case '1.2.840.10065.1.12.1.2':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_2;
      case '1.2.840.10065.1.12.1.3':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_3;
      case '1.2.840.10065.1.12.1.4':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_4;
      case '1.2.840.10065.1.12.1.5':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_5;
      case '1.2.840.10065.1.12.1.6':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_6;
      case '1.2.840.10065.1.12.1.7':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_7;
      case '1.2.840.10065.1.12.1.8':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_8;
      case '1.2.840.10065.1.12.1.9':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_9;
      case '1.2.840.10065.1.12.1.10':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_10;
      case '1.2.840.10065.1.12.1.11':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_11;
      case '1.2.840.10065.1.12.1.12':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_12;
      case '1.2.840.10065.1.12.1.13':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_13;
      case '1.2.840.10065.1.12.1.14':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_14;
      case '1.2.840.10065.1.12.1.15':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_15;
      case '1.2.840.10065.1.12.1.16':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_16;
      case '1.2.840.10065.1.12.1.17':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_17;
      case '1.2.840.10065.1.12.1.18':
        return SignatureTypeCodes.value1_2_840_10065_1_12_1_18;
      default:
        throw ArgumentError('Unknown enum value: $str');
    }
  }

  SignatureTypeCodes fromJson(dynamic jsonValue) {
    if (jsonValue is String) {
      return fromString(jsonValue);
    } else {
      throw ArgumentError('Unknown enum value: $jsonValue');
    }
  }
}
