// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars, unused_element, flutter_style_todos

import 'package:fhir_r4/fhir_r4.dart';

/// The type of a statistic, e.g. relative risk or mean
enum StatisticType {
  /// Display: Absolute Median Difference
  /// Definition: Computed by forming the difference between two medians.
  absolute_MedianDiff('absolute-MedianDiff'),

  /// Display: Count
  /// Definition: The number or amount of something
  C25463('C25463'),

  /// Display: Covariance
  /// Definition: The strength of correlation between a set (2 or more) of random variables. The covariance is obtained by forming: cov(x,y)=e([x-e(x)][y-e(y)] where e(x), e(y) is the expected value (mean) of variable x and y respectively. Covariance is symmetric so cov(x,y)=cov(y,x). The covariance is usefull when looking at the variance of the sum of the 2 random variables since: var(x+y) = var(x) +var(y) +2cov(x,y) the covariance cov(x,y) is used to obtain the coefficient of correlation cor(x,y) by normalizing (dividing) cov(x,y) but the product of the standard deviations of x and y.
  value0000301('0000301'),

  /// Display: Predicted Risk
  /// Definition: A special use case where the proportion is derived from a formula rather than derived from summary evidence.
  predictedRisk('predictedRisk'),

  /// Display: Descriptive
  /// Definition: Descriptive measure reported as narrative.
  descriptive('descriptive'),

  /// Display: Hazard Ratio
  /// Definition: A measure of how often a particular event happens in one group compared to how often it happens in another group, over time. In cancer research, hazard ratios are often used in clinical trials to measure survival at any point in time in a group of patients who have been given a specific treatment compared to a control group given another treatment or a placebo. A hazard ratio of one means that there is no difference in survival between the two groups. A hazard ratio of greater than one or less than one means that survival was better in one of the groups.
  C93150('C93150'),

  /// Display: Incidence
  /// Definition: The relative frequency of occurrence of something.
  C16726('C16726'),

  /// Display: Incidence Rate Ratio
  /// Definition: A type of relative effect estimate that compares rates over time (eg events per person-years).
  rate_ratio('rate-ratio'),

  /// Display: Maximum
  /// Definition: The largest possible quantity or degree.
  C25564('C25564'),

  /// Display: Mean
  /// Definition: The sum of a set of values divided by the number of values in the set.
  C53319('C53319'),

  /// Display: Mean Difference
  /// Definition: The mean difference, or difference in means, measures the absolute difference between the mean value in two different groups.
  value0000457('0000457'),

  /// Display: Median
  /// Definition: The value which has an equal number of values greater and less than it.
  C28007('C28007'),

  /// Display: Minimum
  /// Definition: The smallest possible quantity.
  C25570('C25570'),

  /// Display: Odds Ratio
  /// Definition: The ratio of the odds of an event occurring in one group to the odds of it occurring in another group, or to a sample-based estimate of that ratio.
  C16932('C16932'),

  /// Display: Pearson Correlation Coefficient
  /// Definition: A measure of the correlation of two variables X and Y measured on the same object or organism, that is, a measure of the tendency of the variables to increase or decrease together. It is defined as the sum of the products of the standard scores of the two measures divided by the degrees of freedom.
  C65172('C65172'),

  /// Display: Prevalence
  /// Definition: The ratio (for a given time period) of the number of occurrences of a disease or event to the number of units at risk in the population.
  C17010('C17010'),

  /// Display: Proportion
  /// Definition: Quotient of quantities of the same kind for different components within the same system. [Use for univariate outcomes within an individual.]
  C44256('C44256'),

  /// Display: Regression Coefficient
  /// Definition: Generated by a type of data transformation called a regression, which aims to model a response variable by expression the predictor variables as part of a function where variable terms are modified by a number. A regression coefficient is one such number.
  value0000565('0000565'),

  /// Display: Relative Risk
  /// Definition: A measure of the risk of a certain event happening in one group compared to the risk of the same event happening in another group. In cancer research, risk ratios are used in prospective (forward looking) studies, such as cohort studies and clinical trials. A risk ratio of one means there is no difference between two groups in terms of their risk of cancer, based on whether or not they were exposed to a certain substance or factor, or how they responded to two treatments being compared. A risk ratio of greater than one or of less than one usually means that being exposed to a certain substance or factor either increases (risk ratio greater than one) or decreases (risk ratio less than one) the risk of cancer, or that the treatments being compared do not have the same effects.
  C93152('C93152'),

  /// Display: Risk Difference
  /// Definition: Difference between the observed risks (proportions of individuals with the outcome of interest) in the two groups. The risk difference is straightforward to interpret: it describes the actual difference in the observed risk of events between experimental and control interventions.
  value0000424('0000424'),

  /// Display: Spearman Rank-Order Correlation
  /// Definition: A distribution-free analog of correlation analysis. Like regression, it can be applied to compare two independent random variables, each at several levels (which may be discrete or continuous). Unlike regression, Spearman's rank correlation works on ranked (relative) data, rather than directly on the data itself.
  C65171('C65171'),

  /// Display: Standardized Mean Difference
  /// Definition: Computed by forming the difference between two means, divided by an estimate of the within-group standard deviation. It is used to provide an estimatation of the effect size between two treatments when the predictor (independent variable) is categorical and the response(dependent) variable is continuous
  value0000100('0000100'),

  /// For instances where an Element is present but not value

  elementOnly(''),
  ;

  const StatisticType(this.fhirCode, [this.element]);

  /// The String value of this enum
  final String fhirCode;

  /// The Element value of this enum
  final Element? element;

  /// Serializes the instance to JSON with standardized keys
  Map<String, dynamic> toJson() => {
        'value': fhirCode.isEmpty ? null : fhirCode,
        if (element != null) '_value': element!.toJson(),
      };

  /// Converts a list of JSON values to a list of [StatisticType] instances.
  static StatisticType fromJson(
    Map<String, dynamic> json,
  ) {
    final value = json['value'] as String?;
    final elementJson = json['_value'] as Map<String, dynamic>?;
    final element = elementJson != null ? Element.fromJson(elementJson) : null;
    if (value == null && element != null) {
      return StatisticType.elementOnly.withElement(element);
    }
    return StatisticType.values.firstWhere(
      (e) => e.fhirCode == value,
    );
  }

  /// Returns the enum value with an element
  StatisticType withElement(Element? newElement) {
    return StatisticType.fromJson({
      'value': fhirCode,
      '_value': newElement?.toJson(),
    });
  }
}
