import 'package:fhir_r4/fhir_r4.dart';

/// This function accepts a dynamic value, and a String type and attmpts
/// to create that FhirType
FhirBase? emptyFromType(String type) {
  final fhirType = type.toLowerCase();
  switch (fhirType) {
    case 'fhirbase64binary':
      return FhirBase64Binary.empty();
    case 'base64binary':
      return FhirBase64Binary.empty();
    case 'fhirboolean':
      return FhirBoolean.empty();
    case 'boolean':
      return FhirBoolean.empty();
    case 'fhircanonical':
      return FhirCanonical.empty();
    case 'canonical':
      return FhirCanonical.empty();
    case 'fhircode':
      return FhirCode.empty();
    case 'code':
      return FhirCode.empty();
    case 'fhirdate':
      return FhirDate.empty();
    case 'date':
      return FhirDate.empty();
    case 'fhirdatetime':
      return FhirDateTime.empty();
    case 'datetime':
      return FhirDateTime.empty();
    case 'fhirdecimal':
      return FhirDecimal.empty();
    case 'decimal':
      return FhirDecimal.empty();
    case 'fhirid':
      return FhirId.empty();
    case 'id':
      return FhirId.empty();
    case 'fhirinstant':
      return FhirInstant.empty();
    case 'instant':
      return FhirInstant.empty();
    case 'fhirinteger':
      return FhirInteger.empty();
    case 'integer':
      return FhirInteger.empty();
    case 'fhirmarkdown':
      return FhirMarkdown.empty();
    case 'markdown':
      return FhirMarkdown.empty();
    case 'fhiroid':
      return FhirOid.empty();
    case 'oid':
      return FhirOid.empty();
    case 'fhirpositiveint':
      return FhirPositiveInt.empty();
    case 'positiveint':
      return FhirPositiveInt.empty();
    case 'fhirstring':
      return FhirString.empty();
    case 'string':
      return FhirString.empty();
    case 'fhirtime':
      return FhirTime.empty();
    case 'time':
      return FhirTime.empty();
    case 'fhirunsignedint':
      return FhirUnsignedInt.empty();
    case 'unsignedint':
      return FhirUnsignedInt.empty();
    case 'fhiruri':
      return FhirUri.empty();
    case 'uri':
      return FhirUri.empty();
    case 'fhirurl':
      return FhirUrl.empty();
    case 'url':
      return FhirUrl.empty();
    case 'fhiruuid':
      return FhirUuid.empty();
    case 'uuid':
      return FhirUuid.empty();
    case 'fhirxhtml':
      return FhirXhtml.empty();
    case 'xhtml':
      return FhirXhtml.empty();
    case 'element':
      return Element.empty();
    case 'fhirextension':
      return FhirExtension.empty();
    case 'extension':
      return FhirExtension.empty();
    case 'narrative':
      return Narrative.empty();
    case 'annotation':
      return Annotation.empty();
    case 'attachment':
      return Attachment.empty();
    case 'identifier':
      return Identifier.empty();
    case 'codeableconcept':
      return CodeableConcept.empty();
    case 'codeablereference':
      return CodeableReference.empty();
    case 'coding':
      return Coding.empty();
    case 'quantity':
      return Quantity.empty();
    case 'fhirduration':
      return FhirDuration.empty();
    case 'duration':
      return FhirDuration.empty();
    case 'distance':
      return Distance.empty();
    case 'count':
      return Count.empty();
    case 'money':
      return Money.empty();
    case 'age':
      return Age.empty();
    case 'range':
      return Range.empty();
    case 'period':
      return Period.empty();
    case 'ratio':
      return Ratio.empty();
    case 'ratiorange':
      return RatioRange.empty();
    case 'reference':
      return Reference.empty();
    case 'sampleddata':
      return SampledData.empty();
    case 'signature':
      return Signature.empty();
    case 'humanname':
      return HumanName.empty();
    case 'address':
      return Address.empty();
    case 'contactpoint':
      return ContactPoint.empty();
    case 'timing':
      return Timing.empty();
    case 'timingrepeat':
      return TimingRepeat.empty();
    case 'timing_repeat':
      return TimingRepeat.empty();
    case 'fhirmeta':
      return FhirMeta.empty();
    case 'meta':
      return FhirMeta.empty();
    case 'contactdetail':
      return ContactDetail.empty();
    case 'contributor':
      return Contributor.empty();
    case 'datarequirement':
      return DataRequirement.empty();
    case 'datarequirementcodefilter':
      return DataRequirementCodeFilter.empty();
    case 'datarequirement_codefilter':
      return DataRequirementCodeFilter.empty();
    case 'datarequirementdatefilter':
      return DataRequirementDateFilter.empty();
    case 'datarequirement_datefilter':
      return DataRequirementDateFilter.empty();
    case 'datarequirementsort':
      return DataRequirementSort.empty();
    case 'datarequirement_sort':
      return DataRequirementSort.empty();
    case 'parameterdefinition':
      return ParameterDefinition.empty();
    case 'relatedartifact':
      return RelatedArtifact.empty();
    case 'triggerdefinition':
      return TriggerDefinition.empty();
    case 'usagecontext':
      return UsageContext.empty();
    case 'dosage':
      return Dosage.empty();
    case 'dosagedoseandrate':
      return DosageDoseAndRate.empty();
    case 'dosage_doseandrate':
      return DosageDoseAndRate.empty();
    case 'population':
      return Population.empty();
    case 'productshelflife':
      return ProductShelfLife.empty();
    case 'prodcharacteristic':
      return ProdCharacteristic.empty();
    case 'marketingstatus':
      return MarketingStatus.empty();
    case 'fhirexpression':
      return FhirExpression.empty();
    case 'expression':
      return FhirExpression.empty();
    case 'elementdefinition':
      return ElementDefinition.empty();
    case 'elementdefinitionslicing':
      return ElementDefinitionSlicing.empty();
    case 'elementdefinition_slicing':
      return ElementDefinitionSlicing.empty();
    case 'elementdefinitiondiscriminator':
      return ElementDefinitionDiscriminator.empty();
    case 'elementdefinition_discriminator':
      return ElementDefinitionDiscriminator.empty();
    case 'elementdefinitionbase':
      return ElementDefinitionBase.empty();
    case 'elementdefinition_base':
      return ElementDefinitionBase.empty();
    case 'elementdefinitiontype':
      return ElementDefinitionType.empty();
    case 'elementdefinition_type':
      return ElementDefinitionType.empty();
    case 'elementdefinitionexample':
      return ElementDefinitionExample.empty();
    case 'elementdefinition_example':
      return ElementDefinitionExample.empty();
    case 'elementdefinitionconstraint':
      return ElementDefinitionConstraint.empty();
    case 'elementdefinition_constraint':
      return ElementDefinitionConstraint.empty();
    case 'elementdefinitionbinding':
      return ElementDefinitionBinding.empty();
    case 'elementdefinition_binding':
      return ElementDefinitionBinding.empty();
    case 'elementdefinitionmapping':
      return ElementDefinitionMapping.empty();
    case 'elementdefinition_mapping':
      return ElementDefinitionMapping.empty();
    case 'account':
      return Account.empty();
    case 'accountcoverage':
      return AccountCoverage.empty();
    case 'account_coverage':
      return AccountCoverage.empty();
    case 'accountguarantor':
      return AccountGuarantor.empty();
    case 'account_guarantor':
      return AccountGuarantor.empty();
    case 'activitydefinition':
      return ActivityDefinition.empty();
    case 'activitydefinitionparticipant':
      return ActivityDefinitionParticipant.empty();
    case 'activitydefinition_participant':
      return ActivityDefinitionParticipant.empty();
    case 'activitydefinitiondynamicvalue':
      return ActivityDefinitionDynamicValue.empty();
    case 'activitydefinition_dynamicvalue':
      return ActivityDefinitionDynamicValue.empty();
    case 'administrableproductdefinition':
      return AdministrableProductDefinition.empty();
    case 'administrableproductdefinitionproperty':
      return AdministrableProductDefinitionProperty.empty();
    case 'administrableproductdefinition_property':
      return AdministrableProductDefinitionProperty.empty();
    case 'administrableproductdefinitionrouteofadministration':
      return AdministrableProductDefinitionRouteOfAdministration.empty();
    case 'administrableproductdefinition_routeofadministration':
      return AdministrableProductDefinitionRouteOfAdministration.empty();
    case 'administrableproductdefinitiontargetspecies':
      return AdministrableProductDefinitionTargetSpecies.empty();
    case 'administrableproductdefinition_targetspecies':
      return AdministrableProductDefinitionTargetSpecies.empty();
    case 'administrableproductdefinitionwithdrawalperiod':
      return AdministrableProductDefinitionWithdrawalPeriod.empty();
    case 'administrableproductdefinition_withdrawalperiod':
      return AdministrableProductDefinitionWithdrawalPeriod.empty();
    case 'adverseevent':
      return AdverseEvent.empty();
    case 'adverseeventsuspectentity':
      return AdverseEventSuspectEntity.empty();
    case 'adverseevent_suspectentity':
      return AdverseEventSuspectEntity.empty();
    case 'adverseeventcausality':
      return AdverseEventCausality.empty();
    case 'adverseevent_causality':
      return AdverseEventCausality.empty();
    case 'allergyintolerance':
      return AllergyIntolerance.empty();
    case 'allergyintolerancereaction':
      return AllergyIntoleranceReaction.empty();
    case 'allergyintolerance_reaction':
      return AllergyIntoleranceReaction.empty();
    case 'appointment':
      return Appointment.empty();
    case 'appointmentparticipant':
      return AppointmentParticipant.empty();
    case 'appointment_participant':
      return AppointmentParticipant.empty();
    case 'appointmentresponse':
      return AppointmentResponse.empty();
    case 'auditevent':
      return AuditEvent.empty();
    case 'auditeventagent':
      return AuditEventAgent.empty();
    case 'auditevent_agent':
      return AuditEventAgent.empty();
    case 'auditeventnetwork':
      return AuditEventNetwork.empty();
    case 'auditevent_network':
      return AuditEventNetwork.empty();
    case 'auditeventsource':
      return AuditEventSource.empty();
    case 'auditevent_source':
      return AuditEventSource.empty();
    case 'auditevententity':
      return AuditEventEntity.empty();
    case 'auditevent_entity':
      return AuditEventEntity.empty();
    case 'auditeventdetail':
      return AuditEventDetail.empty();
    case 'auditevent_detail':
      return AuditEventDetail.empty();
    case 'basic':
      return Basic.empty();
    case 'binary':
      return Binary.empty();
    case 'biologicallyderivedproduct':
      return BiologicallyDerivedProduct.empty();
    case 'biologicallyderivedproductcollection':
      return BiologicallyDerivedProductCollection.empty();
    case 'biologicallyderivedproduct_collection':
      return BiologicallyDerivedProductCollection.empty();
    case 'biologicallyderivedproductprocessing':
      return BiologicallyDerivedProductProcessing.empty();
    case 'biologicallyderivedproduct_processing':
      return BiologicallyDerivedProductProcessing.empty();
    case 'biologicallyderivedproductmanipulation':
      return BiologicallyDerivedProductManipulation.empty();
    case 'biologicallyderivedproduct_manipulation':
      return BiologicallyDerivedProductManipulation.empty();
    case 'biologicallyderivedproductstorage':
      return BiologicallyDerivedProductStorage.empty();
    case 'biologicallyderivedproduct_storage':
      return BiologicallyDerivedProductStorage.empty();
    case 'bodystructure':
      return BodyStructure.empty();
    case 'bundle':
      return Bundle.empty();
    case 'bundlelink':
      return BundleLink.empty();
    case 'bundle_link':
      return BundleLink.empty();
    case 'bundleentry':
      return BundleEntry.empty();
    case 'bundle_entry':
      return BundleEntry.empty();
    case 'bundlesearch':
      return BundleSearch.empty();
    case 'bundle_search':
      return BundleSearch.empty();
    case 'bundlerequest':
      return BundleRequest.empty();
    case 'bundle_request':
      return BundleRequest.empty();
    case 'bundleresponse':
      return BundleResponse.empty();
    case 'bundle_response':
      return BundleResponse.empty();
    case 'capabilitystatement':
      return CapabilityStatement.empty();
    case 'capabilitystatementsoftware':
      return CapabilityStatementSoftware.empty();
    case 'capabilitystatement_software':
      return CapabilityStatementSoftware.empty();
    case 'capabilitystatementimplementation':
      return CapabilityStatementImplementation.empty();
    case 'capabilitystatement_implementation':
      return CapabilityStatementImplementation.empty();
    case 'capabilitystatementrest':
      return CapabilityStatementRest.empty();
    case 'capabilitystatement_rest':
      return CapabilityStatementRest.empty();
    case 'capabilitystatementsecurity':
      return CapabilityStatementSecurity.empty();
    case 'capabilitystatement_security':
      return CapabilityStatementSecurity.empty();
    case 'capabilitystatementresource':
      return CapabilityStatementResource.empty();
    case 'capabilitystatement_resource':
      return CapabilityStatementResource.empty();
    case 'capabilitystatementinteraction':
      return CapabilityStatementInteraction.empty();
    case 'capabilitystatement_interaction':
      return CapabilityStatementInteraction.empty();
    case 'capabilitystatementsearchparam':
      return CapabilityStatementSearchParam.empty();
    case 'capabilitystatement_searchparam':
      return CapabilityStatementSearchParam.empty();
    case 'capabilitystatementoperation':
      return CapabilityStatementOperation.empty();
    case 'capabilitystatement_operation':
      return CapabilityStatementOperation.empty();
    case 'capabilitystatementinteraction1':
      return CapabilityStatementInteraction1.empty();
    case 'capabilitystatement_interaction1':
      return CapabilityStatementInteraction1.empty();
    case 'capabilitystatementmessaging':
      return CapabilityStatementMessaging.empty();
    case 'capabilitystatement_messaging':
      return CapabilityStatementMessaging.empty();
    case 'capabilitystatementendpoint':
      return CapabilityStatementEndpoint.empty();
    case 'capabilitystatement_endpoint':
      return CapabilityStatementEndpoint.empty();
    case 'capabilitystatementsupportedmessage':
      return CapabilityStatementSupportedMessage.empty();
    case 'capabilitystatement_supportedmessage':
      return CapabilityStatementSupportedMessage.empty();
    case 'capabilitystatementdocument':
      return CapabilityStatementDocument.empty();
    case 'capabilitystatement_document':
      return CapabilityStatementDocument.empty();
    case 'careplan':
      return CarePlan.empty();
    case 'careplanactivity':
      return CarePlanActivity.empty();
    case 'careplan_activity':
      return CarePlanActivity.empty();
    case 'careplandetail':
      return CarePlanDetail.empty();
    case 'careplan_detail':
      return CarePlanDetail.empty();
    case 'careteam':
      return CareTeam.empty();
    case 'careteamparticipant':
      return CareTeamParticipant.empty();
    case 'careteam_participant':
      return CareTeamParticipant.empty();
    case 'catalogentry':
      return CatalogEntry.empty();
    case 'catalogentryrelatedentry':
      return CatalogEntryRelatedEntry.empty();
    case 'catalogentry_relatedentry':
      return CatalogEntryRelatedEntry.empty();
    case 'chargeitem':
      return ChargeItem.empty();
    case 'chargeitemperformer':
      return ChargeItemPerformer.empty();
    case 'chargeitem_performer':
      return ChargeItemPerformer.empty();
    case 'chargeitemdefinition':
      return ChargeItemDefinition.empty();
    case 'chargeitemdefinitionapplicability':
      return ChargeItemDefinitionApplicability.empty();
    case 'chargeitemdefinition_applicability':
      return ChargeItemDefinitionApplicability.empty();
    case 'chargeitemdefinitionpropertygroup':
      return ChargeItemDefinitionPropertyGroup.empty();
    case 'chargeitemdefinition_propertygroup':
      return ChargeItemDefinitionPropertyGroup.empty();
    case 'chargeitemdefinitionpricecomponent':
      return ChargeItemDefinitionPriceComponent.empty();
    case 'chargeitemdefinition_pricecomponent':
      return ChargeItemDefinitionPriceComponent.empty();
    case 'citation':
      return Citation.empty();
    case 'citationsummary':
      return CitationSummary.empty();
    case 'citation_summary':
      return CitationSummary.empty();
    case 'citationclassification':
      return CitationClassification.empty();
    case 'citation_classification':
      return CitationClassification.empty();
    case 'citationstatusdate':
      return CitationStatusDate.empty();
    case 'citation_statusdate':
      return CitationStatusDate.empty();
    case 'citationrelatesto':
      return CitationRelatesTo.empty();
    case 'citation_relatesto':
      return CitationRelatesTo.empty();
    case 'citationcitedartifact':
      return CitationCitedArtifact.empty();
    case 'citation_citedartifact':
      return CitationCitedArtifact.empty();
    case 'citationversion':
      return CitationVersion.empty();
    case 'citation_version':
      return CitationVersion.empty();
    case 'citationstatusdate1':
      return CitationStatusDate1.empty();
    case 'citation_statusdate1':
      return CitationStatusDate1.empty();
    case 'citationtitle':
      return CitationTitle.empty();
    case 'citation_title':
      return CitationTitle.empty();
    case 'citationabstract':
      return CitationAbstract.empty();
    case 'citation_abstract':
      return CitationAbstract.empty();
    case 'citationpart':
      return CitationPart.empty();
    case 'citation_part':
      return CitationPart.empty();
    case 'citationrelatesto1':
      return CitationRelatesTo1.empty();
    case 'citation_relatesto1':
      return CitationRelatesTo1.empty();
    case 'citationpublicationform':
      return CitationPublicationForm.empty();
    case 'citation_publicationform':
      return CitationPublicationForm.empty();
    case 'citationpublishedin':
      return CitationPublishedIn.empty();
    case 'citation_publishedin':
      return CitationPublishedIn.empty();
    case 'citationperiodicrelease':
      return CitationPeriodicRelease.empty();
    case 'citation_periodicrelease':
      return CitationPeriodicRelease.empty();
    case 'citationdateofpublication':
      return CitationDateOfPublication.empty();
    case 'citation_dateofpublication':
      return CitationDateOfPublication.empty();
    case 'citationweblocation':
      return CitationWebLocation.empty();
    case 'citation_weblocation':
      return CitationWebLocation.empty();
    case 'citationclassification1':
      return CitationClassification1.empty();
    case 'citation_classification1':
      return CitationClassification1.empty();
    case 'citationwhoclassified':
      return CitationWhoClassified.empty();
    case 'citation_whoclassified':
      return CitationWhoClassified.empty();
    case 'citationcontributorship':
      return CitationContributorship.empty();
    case 'citation_contributorship':
      return CitationContributorship.empty();
    case 'citationentry':
      return CitationEntry.empty();
    case 'citation_entry':
      return CitationEntry.empty();
    case 'citationaffiliationinfo':
      return CitationAffiliationInfo.empty();
    case 'citation_affiliationinfo':
      return CitationAffiliationInfo.empty();
    case 'citationcontributioninstance':
      return CitationContributionInstance.empty();
    case 'citation_contributioninstance':
      return CitationContributionInstance.empty();
    case 'citationsummary1':
      return CitationSummary1.empty();
    case 'citation_summary1':
      return CitationSummary1.empty();
    case 'claim':
      return Claim.empty();
    case 'claimrelated':
      return ClaimRelated.empty();
    case 'claim_related':
      return ClaimRelated.empty();
    case 'claimpayee':
      return ClaimPayee.empty();
    case 'claim_payee':
      return ClaimPayee.empty();
    case 'claimcareteam':
      return ClaimCareTeam.empty();
    case 'claim_careteam':
      return ClaimCareTeam.empty();
    case 'claimsupportinginfo':
      return ClaimSupportingInfo.empty();
    case 'claim_supportinginfo':
      return ClaimSupportingInfo.empty();
    case 'claimdiagnosis':
      return ClaimDiagnosis.empty();
    case 'claim_diagnosis':
      return ClaimDiagnosis.empty();
    case 'claimprocedure':
      return ClaimProcedure.empty();
    case 'claim_procedure':
      return ClaimProcedure.empty();
    case 'claiminsurance':
      return ClaimInsurance.empty();
    case 'claim_insurance':
      return ClaimInsurance.empty();
    case 'claimaccident':
      return ClaimAccident.empty();
    case 'claim_accident':
      return ClaimAccident.empty();
    case 'claimitem':
      return ClaimItem.empty();
    case 'claim_item':
      return ClaimItem.empty();
    case 'claimdetail':
      return ClaimDetail.empty();
    case 'claim_detail':
      return ClaimDetail.empty();
    case 'claimsubdetail':
      return ClaimSubDetail.empty();
    case 'claim_subdetail':
      return ClaimSubDetail.empty();
    case 'claimresponse':
      return ClaimResponse.empty();
    case 'claimresponseitem':
      return ClaimResponseItem.empty();
    case 'claimresponse_item':
      return ClaimResponseItem.empty();
    case 'claimresponseadjudication':
      return ClaimResponseAdjudication.empty();
    case 'claimresponse_adjudication':
      return ClaimResponseAdjudication.empty();
    case 'claimresponsedetail':
      return ClaimResponseDetail.empty();
    case 'claimresponse_detail':
      return ClaimResponseDetail.empty();
    case 'claimresponsesubdetail':
      return ClaimResponseSubDetail.empty();
    case 'claimresponse_subdetail':
      return ClaimResponseSubDetail.empty();
    case 'claimresponseadditem':
      return ClaimResponseAddItem.empty();
    case 'claimresponse_additem':
      return ClaimResponseAddItem.empty();
    case 'claimresponsedetail1':
      return ClaimResponseDetail1.empty();
    case 'claimresponse_detail1':
      return ClaimResponseDetail1.empty();
    case 'claimresponsesubdetail1':
      return ClaimResponseSubDetail1.empty();
    case 'claimresponse_subdetail1':
      return ClaimResponseSubDetail1.empty();
    case 'claimresponsetotal':
      return ClaimResponseTotal.empty();
    case 'claimresponse_total':
      return ClaimResponseTotal.empty();
    case 'claimresponsepayment':
      return ClaimResponsePayment.empty();
    case 'claimresponse_payment':
      return ClaimResponsePayment.empty();
    case 'claimresponseprocessnote':
      return ClaimResponseProcessNote.empty();
    case 'claimresponse_processnote':
      return ClaimResponseProcessNote.empty();
    case 'claimresponseinsurance':
      return ClaimResponseInsurance.empty();
    case 'claimresponse_insurance':
      return ClaimResponseInsurance.empty();
    case 'claimresponseerror':
      return ClaimResponseError.empty();
    case 'claimresponse_error':
      return ClaimResponseError.empty();
    case 'clinicalimpression':
      return ClinicalImpression.empty();
    case 'clinicalimpressioninvestigation':
      return ClinicalImpressionInvestigation.empty();
    case 'clinicalimpression_investigation':
      return ClinicalImpressionInvestigation.empty();
    case 'clinicalimpressionfinding':
      return ClinicalImpressionFinding.empty();
    case 'clinicalimpression_finding':
      return ClinicalImpressionFinding.empty();
    case 'clinicalusedefinition':
      return ClinicalUseDefinition.empty();
    case 'clinicalusedefinitioncontraindication':
      return ClinicalUseDefinitionContraindication.empty();
    case 'clinicalusedefinition_contraindication':
      return ClinicalUseDefinitionContraindication.empty();
    case 'clinicalusedefinitionothertherapy':
      return ClinicalUseDefinitionOtherTherapy.empty();
    case 'clinicalusedefinition_othertherapy':
      return ClinicalUseDefinitionOtherTherapy.empty();
    case 'clinicalusedefinitionindication':
      return ClinicalUseDefinitionIndication.empty();
    case 'clinicalusedefinition_indication':
      return ClinicalUseDefinitionIndication.empty();
    case 'clinicalusedefinitioninteraction':
      return ClinicalUseDefinitionInteraction.empty();
    case 'clinicalusedefinition_interaction':
      return ClinicalUseDefinitionInteraction.empty();
    case 'clinicalusedefinitioninteractant':
      return ClinicalUseDefinitionInteractant.empty();
    case 'clinicalusedefinition_interactant':
      return ClinicalUseDefinitionInteractant.empty();
    case 'clinicalusedefinitionundesirableeffect':
      return ClinicalUseDefinitionUndesirableEffect.empty();
    case 'clinicalusedefinition_undesirableeffect':
      return ClinicalUseDefinitionUndesirableEffect.empty();
    case 'clinicalusedefinitionwarning':
      return ClinicalUseDefinitionWarning.empty();
    case 'clinicalusedefinition_warning':
      return ClinicalUseDefinitionWarning.empty();
    case 'codesystem':
      return CodeSystem.empty();
    case 'codesystemfilter':
      return CodeSystemFilter.empty();
    case 'codesystem_filter':
      return CodeSystemFilter.empty();
    case 'codesystemproperty':
      return CodeSystemProperty.empty();
    case 'codesystem_property':
      return CodeSystemProperty.empty();
    case 'codesystemconcept':
      return CodeSystemConcept.empty();
    case 'codesystem_concept':
      return CodeSystemConcept.empty();
    case 'codesystemdesignation':
      return CodeSystemDesignation.empty();
    case 'codesystem_designation':
      return CodeSystemDesignation.empty();
    case 'codesystemproperty1':
      return CodeSystemProperty1.empty();
    case 'codesystem_property1':
      return CodeSystemProperty1.empty();
    case 'communication':
      return Communication.empty();
    case 'communicationpayload':
      return CommunicationPayload.empty();
    case 'communication_payload':
      return CommunicationPayload.empty();
    case 'communicationrequest':
      return CommunicationRequest.empty();
    case 'communicationrequestpayload':
      return CommunicationRequestPayload.empty();
    case 'communicationrequest_payload':
      return CommunicationRequestPayload.empty();
    case 'compartmentdefinition':
      return CompartmentDefinition.empty();
    case 'compartmentdefinitionresource':
      return CompartmentDefinitionResource.empty();
    case 'compartmentdefinition_resource':
      return CompartmentDefinitionResource.empty();
    case 'composition':
      return Composition.empty();
    case 'compositionattester':
      return CompositionAttester.empty();
    case 'composition_attester':
      return CompositionAttester.empty();
    case 'compositionrelatesto':
      return CompositionRelatesTo.empty();
    case 'composition_relatesto':
      return CompositionRelatesTo.empty();
    case 'compositionevent':
      return CompositionEvent.empty();
    case 'composition_event':
      return CompositionEvent.empty();
    case 'compositionsection':
      return CompositionSection.empty();
    case 'composition_section':
      return CompositionSection.empty();
    case 'conceptmap':
      return ConceptMap.empty();
    case 'conceptmapgroup':
      return ConceptMapGroup.empty();
    case 'conceptmap_group':
      return ConceptMapGroup.empty();
    case 'conceptmapelement':
      return ConceptMapElement.empty();
    case 'conceptmap_element':
      return ConceptMapElement.empty();
    case 'conceptmaptarget':
      return ConceptMapTarget.empty();
    case 'conceptmap_target':
      return ConceptMapTarget.empty();
    case 'conceptmapdependson':
      return ConceptMapDependsOn.empty();
    case 'conceptmap_dependson':
      return ConceptMapDependsOn.empty();
    case 'conceptmapunmapped':
      return ConceptMapUnmapped.empty();
    case 'conceptmap_unmapped':
      return ConceptMapUnmapped.empty();
    case 'condition':
      return Condition.empty();
    case 'conditionstage':
      return ConditionStage.empty();
    case 'condition_stage':
      return ConditionStage.empty();
    case 'conditionevidence':
      return ConditionEvidence.empty();
    case 'condition_evidence':
      return ConditionEvidence.empty();
    case 'consent':
      return Consent.empty();
    case 'consentpolicy':
      return ConsentPolicy.empty();
    case 'consent_policy':
      return ConsentPolicy.empty();
    case 'consentverification':
      return ConsentVerification.empty();
    case 'consent_verification':
      return ConsentVerification.empty();
    case 'consentprovision':
      return ConsentProvision.empty();
    case 'consent_provision':
      return ConsentProvision.empty();
    case 'consentactor':
      return ConsentActor.empty();
    case 'consent_actor':
      return ConsentActor.empty();
    case 'consentdata':
      return ConsentData.empty();
    case 'consent_data':
      return ConsentData.empty();
    case 'contract':
      return Contract.empty();
    case 'contractcontentdefinition':
      return ContractContentDefinition.empty();
    case 'contract_contentdefinition':
      return ContractContentDefinition.empty();
    case 'contractterm':
      return ContractTerm.empty();
    case 'contract_term':
      return ContractTerm.empty();
    case 'contractsecuritylabel':
      return ContractSecurityLabel.empty();
    case 'contract_securitylabel':
      return ContractSecurityLabel.empty();
    case 'contractoffer':
      return ContractOffer.empty();
    case 'contract_offer':
      return ContractOffer.empty();
    case 'contractparty':
      return ContractParty.empty();
    case 'contract_party':
      return ContractParty.empty();
    case 'contractanswer':
      return ContractAnswer.empty();
    case 'contract_answer':
      return ContractAnswer.empty();
    case 'contractasset':
      return ContractAsset.empty();
    case 'contract_asset':
      return ContractAsset.empty();
    case 'contractcontext':
      return ContractContext.empty();
    case 'contract_context':
      return ContractContext.empty();
    case 'contractvalueditem':
      return ContractValuedItem.empty();
    case 'contract_valueditem':
      return ContractValuedItem.empty();
    case 'contractaction':
      return ContractAction.empty();
    case 'contract_action':
      return ContractAction.empty();
    case 'contractsubject':
      return ContractSubject.empty();
    case 'contract_subject':
      return ContractSubject.empty();
    case 'contractsigner':
      return ContractSigner.empty();
    case 'contract_signer':
      return ContractSigner.empty();
    case 'contractfriendly':
      return ContractFriendly.empty();
    case 'contract_friendly':
      return ContractFriendly.empty();
    case 'contractlegal':
      return ContractLegal.empty();
    case 'contract_legal':
      return ContractLegal.empty();
    case 'contractrule':
      return ContractRule.empty();
    case 'contract_rule':
      return ContractRule.empty();
    case 'coverage':
      return Coverage.empty();
    case 'coverageclass':
      return CoverageClass.empty();
    case 'coverage_class':
      return CoverageClass.empty();
    case 'coveragecosttobeneficiary':
      return CoverageCostToBeneficiary.empty();
    case 'coverage_costtobeneficiary':
      return CoverageCostToBeneficiary.empty();
    case 'coverageexception':
      return CoverageException.empty();
    case 'coverage_exception':
      return CoverageException.empty();
    case 'coverageeligibilityrequest':
      return CoverageEligibilityRequest.empty();
    case 'coverageeligibilityrequestsupportinginfo':
      return CoverageEligibilityRequestSupportingInfo.empty();
    case 'coverageeligibilityrequest_supportinginfo':
      return CoverageEligibilityRequestSupportingInfo.empty();
    case 'coverageeligibilityrequestinsurance':
      return CoverageEligibilityRequestInsurance.empty();
    case 'coverageeligibilityrequest_insurance':
      return CoverageEligibilityRequestInsurance.empty();
    case 'coverageeligibilityrequestitem':
      return CoverageEligibilityRequestItem.empty();
    case 'coverageeligibilityrequest_item':
      return CoverageEligibilityRequestItem.empty();
    case 'coverageeligibilityrequestdiagnosis':
      return CoverageEligibilityRequestDiagnosis.empty();
    case 'coverageeligibilityrequest_diagnosis':
      return CoverageEligibilityRequestDiagnosis.empty();
    case 'coverageeligibilityresponse':
      return CoverageEligibilityResponse.empty();
    case 'coverageeligibilityresponseinsurance':
      return CoverageEligibilityResponseInsurance.empty();
    case 'coverageeligibilityresponse_insurance':
      return CoverageEligibilityResponseInsurance.empty();
    case 'coverageeligibilityresponseitem':
      return CoverageEligibilityResponseItem.empty();
    case 'coverageeligibilityresponse_item':
      return CoverageEligibilityResponseItem.empty();
    case 'coverageeligibilityresponsebenefit':
      return CoverageEligibilityResponseBenefit.empty();
    case 'coverageeligibilityresponse_benefit':
      return CoverageEligibilityResponseBenefit.empty();
    case 'coverageeligibilityresponseerror':
      return CoverageEligibilityResponseError.empty();
    case 'coverageeligibilityresponse_error':
      return CoverageEligibilityResponseError.empty();
    case 'detectedissue':
      return DetectedIssue.empty();
    case 'detectedissueevidence':
      return DetectedIssueEvidence.empty();
    case 'detectedissue_evidence':
      return DetectedIssueEvidence.empty();
    case 'detectedissuemitigation':
      return DetectedIssueMitigation.empty();
    case 'detectedissue_mitigation':
      return DetectedIssueMitigation.empty();
    case 'device':
      return Device.empty();
    case 'deviceudicarrier':
      return DeviceUdiCarrier.empty();
    case 'device_udicarrier':
      return DeviceUdiCarrier.empty();
    case 'devicedevicename':
      return DeviceDeviceName.empty();
    case 'device_devicename':
      return DeviceDeviceName.empty();
    case 'devicespecialization':
      return DeviceSpecialization.empty();
    case 'device_specialization':
      return DeviceSpecialization.empty();
    case 'deviceversion':
      return DeviceVersion.empty();
    case 'device_version':
      return DeviceVersion.empty();
    case 'deviceproperty':
      return DeviceProperty.empty();
    case 'device_property':
      return DeviceProperty.empty();
    case 'devicedefinition':
      return DeviceDefinition.empty();
    case 'devicedefinitionudideviceidentifier':
      return DeviceDefinitionUdiDeviceIdentifier.empty();
    case 'devicedefinition_udideviceidentifier':
      return DeviceDefinitionUdiDeviceIdentifier.empty();
    case 'devicedefinitiondevicename':
      return DeviceDefinitionDeviceName.empty();
    case 'devicedefinition_devicename':
      return DeviceDefinitionDeviceName.empty();
    case 'devicedefinitionspecialization':
      return DeviceDefinitionSpecialization.empty();
    case 'devicedefinition_specialization':
      return DeviceDefinitionSpecialization.empty();
    case 'devicedefinitioncapability':
      return DeviceDefinitionCapability.empty();
    case 'devicedefinition_capability':
      return DeviceDefinitionCapability.empty();
    case 'devicedefinitionproperty':
      return DeviceDefinitionProperty.empty();
    case 'devicedefinition_property':
      return DeviceDefinitionProperty.empty();
    case 'devicedefinitionmaterial':
      return DeviceDefinitionMaterial.empty();
    case 'devicedefinition_material':
      return DeviceDefinitionMaterial.empty();
    case 'devicemetric':
      return DeviceMetric.empty();
    case 'devicemetriccalibration':
      return DeviceMetricCalibration.empty();
    case 'devicemetric_calibration':
      return DeviceMetricCalibration.empty();
    case 'devicerequest':
      return DeviceRequest.empty();
    case 'devicerequestparameter':
      return DeviceRequestParameter.empty();
    case 'devicerequest_parameter':
      return DeviceRequestParameter.empty();
    case 'deviceusestatement':
      return DeviceUseStatement.empty();
    case 'diagnosticreport':
      return DiagnosticReport.empty();
    case 'diagnosticreportmedia':
      return DiagnosticReportMedia.empty();
    case 'diagnosticreport_media':
      return DiagnosticReportMedia.empty();
    case 'documentmanifest':
      return DocumentManifest.empty();
    case 'documentmanifestrelated':
      return DocumentManifestRelated.empty();
    case 'documentmanifest_related':
      return DocumentManifestRelated.empty();
    case 'documentreference':
      return DocumentReference.empty();
    case 'documentreferencerelatesto':
      return DocumentReferenceRelatesTo.empty();
    case 'documentreference_relatesto':
      return DocumentReferenceRelatesTo.empty();
    case 'documentreferencecontent':
      return DocumentReferenceContent.empty();
    case 'documentreference_content':
      return DocumentReferenceContent.empty();
    case 'documentreferencecontext':
      return DocumentReferenceContext.empty();
    case 'documentreference_context':
      return DocumentReferenceContext.empty();
    case 'encounter':
      return Encounter.empty();
    case 'encounterstatushistory':
      return EncounterStatusHistory.empty();
    case 'encounter_statushistory':
      return EncounterStatusHistory.empty();
    case 'encounterclasshistory':
      return EncounterClassHistory.empty();
    case 'encounter_classhistory':
      return EncounterClassHistory.empty();
    case 'encounterparticipant':
      return EncounterParticipant.empty();
    case 'encounter_participant':
      return EncounterParticipant.empty();
    case 'encounterdiagnosis':
      return EncounterDiagnosis.empty();
    case 'encounter_diagnosis':
      return EncounterDiagnosis.empty();
    case 'encounterhospitalization':
      return EncounterHospitalization.empty();
    case 'encounter_hospitalization':
      return EncounterHospitalization.empty();
    case 'encounterlocation':
      return EncounterLocation.empty();
    case 'encounter_location':
      return EncounterLocation.empty();
    case 'fhirendpoint':
      return FhirEndpoint.empty();
    case 'endpoint':
      return FhirEndpoint.empty();
    case 'enrollmentrequest':
      return EnrollmentRequest.empty();
    case 'enrollmentresponse':
      return EnrollmentResponse.empty();
    case 'episodeofcare':
      return EpisodeOfCare.empty();
    case 'episodeofcarestatushistory':
      return EpisodeOfCareStatusHistory.empty();
    case 'episodeofcare_statushistory':
      return EpisodeOfCareStatusHistory.empty();
    case 'episodeofcarediagnosis':
      return EpisodeOfCareDiagnosis.empty();
    case 'episodeofcare_diagnosis':
      return EpisodeOfCareDiagnosis.empty();
    case 'eventdefinition':
      return EventDefinition.empty();
    case 'evidence':
      return Evidence.empty();
    case 'evidencevariabledefinition':
      return EvidenceVariableDefinition.empty();
    case 'evidence_variabledefinition':
      return EvidenceVariableDefinition.empty();
    case 'evidencestatistic':
      return EvidenceStatistic.empty();
    case 'evidence_statistic':
      return EvidenceStatistic.empty();
    case 'evidencesamplesize':
      return EvidenceSampleSize.empty();
    case 'evidence_samplesize':
      return EvidenceSampleSize.empty();
    case 'evidenceattributeestimate':
      return EvidenceAttributeEstimate.empty();
    case 'evidence_attributeestimate':
      return EvidenceAttributeEstimate.empty();
    case 'evidencemodelcharacteristic':
      return EvidenceModelCharacteristic.empty();
    case 'evidence_modelcharacteristic':
      return EvidenceModelCharacteristic.empty();
    case 'evidencemodelcharacteristicvariable':
      return EvidenceModelCharacteristicVariable.empty();
    case 'evidence_variable':
      return EvidenceModelCharacteristicVariable.empty();
    case 'evidencevariable':
      return EvidenceModelCharacteristicVariable.empty();
    case 'evidencecertainty':
      return EvidenceCertainty.empty();
    case 'evidence_certainty':
      return EvidenceCertainty.empty();
    case 'evidencereport':
      return EvidenceReport.empty();
    case 'evidencereportsubject':
      return EvidenceReportSubject.empty();
    case 'evidencereport_subject':
      return EvidenceReportSubject.empty();
    case 'evidencereportcharacteristic':
      return EvidenceReportCharacteristic.empty();
    case 'evidencereport_characteristic':
      return EvidenceReportCharacteristic.empty();
    case 'evidencereportrelatesto':
      return EvidenceReportRelatesTo.empty();
    case 'evidencereport_relatesto':
      return EvidenceReportRelatesTo.empty();
    case 'evidencereportsection':
      return EvidenceReportSection.empty();
    case 'evidencereport_section':
      return EvidenceReportSection.empty();
    case 'evidencevariablecharacteristic':
      return EvidenceVariableCharacteristic.empty();
    case 'evidencevariable_characteristic':
      return EvidenceVariableCharacteristic.empty();
    case 'evidencevariabletimefromstart':
      return EvidenceVariableTimeFromStart.empty();
    case 'evidencevariable_timefromstart':
      return EvidenceVariableTimeFromStart.empty();
    case 'evidencevariablecategory':
      return EvidenceVariableCategory.empty();
    case 'evidencevariable_category':
      return EvidenceVariableCategory.empty();
    case 'examplescenario':
      return ExampleScenario.empty();
    case 'examplescenarioactor':
      return ExampleScenarioActor.empty();
    case 'examplescenario_actor':
      return ExampleScenarioActor.empty();
    case 'examplescenarioinstance':
      return ExampleScenarioInstance.empty();
    case 'examplescenario_instance':
      return ExampleScenarioInstance.empty();
    case 'examplescenarioversion':
      return ExampleScenarioVersion.empty();
    case 'examplescenario_version':
      return ExampleScenarioVersion.empty();
    case 'examplescenariocontainedinstance':
      return ExampleScenarioContainedInstance.empty();
    case 'examplescenario_containedinstance':
      return ExampleScenarioContainedInstance.empty();
    case 'examplescenarioprocess':
      return ExampleScenarioProcess.empty();
    case 'examplescenario_process':
      return ExampleScenarioProcess.empty();
    case 'examplescenariostep':
      return ExampleScenarioStep.empty();
    case 'examplescenario_step':
      return ExampleScenarioStep.empty();
    case 'examplescenariooperation':
      return ExampleScenarioOperation.empty();
    case 'examplescenario_operation':
      return ExampleScenarioOperation.empty();
    case 'examplescenarioalternative':
      return ExampleScenarioAlternative.empty();
    case 'examplescenario_alternative':
      return ExampleScenarioAlternative.empty();
    case 'explanationofbenefit':
      return ExplanationOfBenefit.empty();
    case 'explanationofbenefitrelated':
      return ExplanationOfBenefitRelated.empty();
    case 'explanationofbenefit_related':
      return ExplanationOfBenefitRelated.empty();
    case 'explanationofbenefitpayee':
      return ExplanationOfBenefitPayee.empty();
    case 'explanationofbenefit_payee':
      return ExplanationOfBenefitPayee.empty();
    case 'explanationofbenefitcareteam':
      return ExplanationOfBenefitCareTeam.empty();
    case 'explanationofbenefit_careteam':
      return ExplanationOfBenefitCareTeam.empty();
    case 'explanationofbenefitsupportinginfo':
      return ExplanationOfBenefitSupportingInfo.empty();
    case 'explanationofbenefit_supportinginfo':
      return ExplanationOfBenefitSupportingInfo.empty();
    case 'explanationofbenefitdiagnosis':
      return ExplanationOfBenefitDiagnosis.empty();
    case 'explanationofbenefit_diagnosis':
      return ExplanationOfBenefitDiagnosis.empty();
    case 'explanationofbenefitprocedure':
      return ExplanationOfBenefitProcedure.empty();
    case 'explanationofbenefit_procedure':
      return ExplanationOfBenefitProcedure.empty();
    case 'explanationofbenefitinsurance':
      return ExplanationOfBenefitInsurance.empty();
    case 'explanationofbenefit_insurance':
      return ExplanationOfBenefitInsurance.empty();
    case 'explanationofbenefitaccident':
      return ExplanationOfBenefitAccident.empty();
    case 'explanationofbenefit_accident':
      return ExplanationOfBenefitAccident.empty();
    case 'explanationofbenefititem':
      return ExplanationOfBenefitItem.empty();
    case 'explanationofbenefit_item':
      return ExplanationOfBenefitItem.empty();
    case 'explanationofbenefitadjudication':
      return ExplanationOfBenefitAdjudication.empty();
    case 'explanationofbenefit_adjudication':
      return ExplanationOfBenefitAdjudication.empty();
    case 'explanationofbenefitdetail':
      return ExplanationOfBenefitDetail.empty();
    case 'explanationofbenefit_detail':
      return ExplanationOfBenefitDetail.empty();
    case 'explanationofbenefitsubdetail':
      return ExplanationOfBenefitSubDetail.empty();
    case 'explanationofbenefit_subdetail':
      return ExplanationOfBenefitSubDetail.empty();
    case 'explanationofbenefitadditem':
      return ExplanationOfBenefitAddItem.empty();
    case 'explanationofbenefit_additem':
      return ExplanationOfBenefitAddItem.empty();
    case 'explanationofbenefitdetail1':
      return ExplanationOfBenefitDetail1.empty();
    case 'explanationofbenefit_detail1':
      return ExplanationOfBenefitDetail1.empty();
    case 'explanationofbenefitsubdetail1':
      return ExplanationOfBenefitSubDetail1.empty();
    case 'explanationofbenefit_subdetail1':
      return ExplanationOfBenefitSubDetail1.empty();
    case 'explanationofbenefittotal':
      return ExplanationOfBenefitTotal.empty();
    case 'explanationofbenefit_total':
      return ExplanationOfBenefitTotal.empty();
    case 'explanationofbenefitpayment':
      return ExplanationOfBenefitPayment.empty();
    case 'explanationofbenefit_payment':
      return ExplanationOfBenefitPayment.empty();
    case 'explanationofbenefitprocessnote':
      return ExplanationOfBenefitProcessNote.empty();
    case 'explanationofbenefit_processnote':
      return ExplanationOfBenefitProcessNote.empty();
    case 'explanationofbenefitbenefitbalance':
      return ExplanationOfBenefitBenefitBalance.empty();
    case 'explanationofbenefit_benefitbalance':
      return ExplanationOfBenefitBenefitBalance.empty();
    case 'explanationofbenefitfinancial':
      return ExplanationOfBenefitFinancial.empty();
    case 'explanationofbenefit_financial':
      return ExplanationOfBenefitFinancial.empty();
    case 'familymemberhistory':
      return FamilyMemberHistory.empty();
    case 'familymemberhistorycondition':
      return FamilyMemberHistoryCondition.empty();
    case 'familymemberhistory_condition':
      return FamilyMemberHistoryCondition.empty();
    case 'flag':
      return Flag.empty();
    case 'goal':
      return Goal.empty();
    case 'goaltarget':
      return GoalTarget.empty();
    case 'goal_target':
      return GoalTarget.empty();
    case 'graphdefinition':
      return GraphDefinition.empty();
    case 'graphdefinitionlink':
      return GraphDefinitionLink.empty();
    case 'graphdefinition_link':
      return GraphDefinitionLink.empty();
    case 'graphdefinitiontarget':
      return GraphDefinitionTarget.empty();
    case 'graphdefinition_target':
      return GraphDefinitionTarget.empty();
    case 'graphdefinitioncompartment':
      return GraphDefinitionCompartment.empty();
    case 'graphdefinition_compartment':
      return GraphDefinitionCompartment.empty();
    case 'fhirgroup':
      return FhirGroup.empty();
    case 'group':
      return FhirGroup.empty();
    case 'groupcharacteristic':
      return GroupCharacteristic.empty();
    case 'group_characteristic':
      return GroupCharacteristic.empty();
    case 'groupmember':
      return GroupMember.empty();
    case 'group_member':
      return GroupMember.empty();
    case 'guidanceresponse':
      return GuidanceResponse.empty();
    case 'healthcareservice':
      return HealthcareService.empty();
    case 'healthcareserviceeligibility':
      return HealthcareServiceEligibility.empty();
    case 'healthcareservice_eligibility':
      return HealthcareServiceEligibility.empty();
    case 'healthcareserviceavailabletime':
      return HealthcareServiceAvailableTime.empty();
    case 'healthcareservice_availabletime':
      return HealthcareServiceAvailableTime.empty();
    case 'healthcareservicenotavailable':
      return HealthcareServiceNotAvailable.empty();
    case 'healthcareservice_notavailable':
      return HealthcareServiceNotAvailable.empty();
    case 'imagingstudy':
      return ImagingStudy.empty();
    case 'imagingstudyseries':
      return ImagingStudySeries.empty();
    case 'imagingstudy_series':
      return ImagingStudySeries.empty();
    case 'imagingstudyperformer':
      return ImagingStudyPerformer.empty();
    case 'imagingstudy_performer':
      return ImagingStudyPerformer.empty();
    case 'imagingstudyinstance':
      return ImagingStudyInstance.empty();
    case 'imagingstudy_instance':
      return ImagingStudyInstance.empty();
    case 'immunization':
      return Immunization.empty();
    case 'immunizationperformer':
      return ImmunizationPerformer.empty();
    case 'immunization_performer':
      return ImmunizationPerformer.empty();
    case 'immunizationeducation':
      return ImmunizationEducation.empty();
    case 'immunization_education':
      return ImmunizationEducation.empty();
    case 'immunizationreaction':
      return ImmunizationReaction.empty();
    case 'immunization_reaction':
      return ImmunizationReaction.empty();
    case 'immunizationprotocolapplied':
      return ImmunizationProtocolApplied.empty();
    case 'immunization_protocolapplied':
      return ImmunizationProtocolApplied.empty();
    case 'immunizationevaluation':
      return ImmunizationEvaluation.empty();
    case 'immunizationrecommendation':
      return ImmunizationRecommendation.empty();
    case 'immunizationrecommendationrecommendation':
      return ImmunizationRecommendationRecommendation.empty();
    case 'immunizationrecommendation_recommendation':
      return ImmunizationRecommendationRecommendation.empty();
    case 'immunizationrecommendationdatecriterion':
      return ImmunizationRecommendationDateCriterion.empty();
    case 'immunizationrecommendation_datecriterion':
      return ImmunizationRecommendationDateCriterion.empty();
    case 'implementationguide':
      return ImplementationGuide.empty();
    case 'implementationguidedependson':
      return ImplementationGuideDependsOn.empty();
    case 'implementationguide_dependson':
      return ImplementationGuideDependsOn.empty();
    case 'implementationguideglobal':
      return ImplementationGuideGlobal.empty();
    case 'implementationguide_global':
      return ImplementationGuideGlobal.empty();
    case 'implementationguidedefinition':
      return ImplementationGuideDefinition.empty();
    case 'implementationguide_definition':
      return ImplementationGuideDefinition.empty();
    case 'implementationguidegrouping':
      return ImplementationGuideGrouping.empty();
    case 'implementationguide_grouping':
      return ImplementationGuideGrouping.empty();
    case 'implementationguideresource':
      return ImplementationGuideResource.empty();
    case 'implementationguide_resource':
      return ImplementationGuideResource.empty();
    case 'implementationguidepage':
      return ImplementationGuidePage.empty();
    case 'implementationguide_page':
      return ImplementationGuidePage.empty();
    case 'implementationguideparameter':
      return ImplementationGuideParameter.empty();
    case 'implementationguide_parameter':
      return ImplementationGuideParameter.empty();
    case 'implementationguidetemplate':
      return ImplementationGuideTemplate.empty();
    case 'implementationguide_template':
      return ImplementationGuideTemplate.empty();
    case 'implementationguidemanifest':
      return ImplementationGuideManifest.empty();
    case 'implementationguide_manifest':
      return ImplementationGuideManifest.empty();
    case 'implementationguideresource1':
      return ImplementationGuideResource1.empty();
    case 'implementationguide_resource1':
      return ImplementationGuideResource1.empty();
    case 'implementationguidepage1':
      return ImplementationGuidePage1.empty();
    case 'implementationguide_page1':
      return ImplementationGuidePage1.empty();
    case 'ingredient':
      return Ingredient.empty();
    case 'ingredientmanufacturer':
      return IngredientManufacturer.empty();
    case 'ingredient_manufacturer':
      return IngredientManufacturer.empty();
    case 'ingredientsubstance':
      return IngredientSubstance.empty();
    case 'ingredient_substance':
      return IngredientSubstance.empty();
    case 'ingredientstrength':
      return IngredientStrength.empty();
    case 'ingredient_strength':
      return IngredientStrength.empty();
    case 'ingredientreferencestrength':
      return IngredientReferenceStrength.empty();
    case 'ingredient_referencestrength':
      return IngredientReferenceStrength.empty();
    case 'insuranceplan':
      return InsurancePlan.empty();
    case 'insuranceplancontact':
      return InsurancePlanContact.empty();
    case 'insuranceplan_contact':
      return InsurancePlanContact.empty();
    case 'insuranceplancoverage':
      return InsurancePlanCoverage.empty();
    case 'insuranceplan_coverage':
      return InsurancePlanCoverage.empty();
    case 'insuranceplanbenefit':
      return InsurancePlanBenefit.empty();
    case 'insuranceplan_benefit':
      return InsurancePlanBenefit.empty();
    case 'insuranceplanlimit':
      return InsurancePlanLimit.empty();
    case 'insuranceplan_limit':
      return InsurancePlanLimit.empty();
    case 'insuranceplanplan':
      return InsurancePlanPlan.empty();
    case 'insuranceplan_plan':
      return InsurancePlanPlan.empty();
    case 'insuranceplangeneralcost':
      return InsurancePlanGeneralCost.empty();
    case 'insuranceplan_generalcost':
      return InsurancePlanGeneralCost.empty();
    case 'insuranceplanspecificcost':
      return InsurancePlanSpecificCost.empty();
    case 'insuranceplan_specificcost':
      return InsurancePlanSpecificCost.empty();
    case 'insuranceplanbenefit1':
      return InsurancePlanBenefit1.empty();
    case 'insuranceplan_benefit1':
      return InsurancePlanBenefit1.empty();
    case 'insuranceplancost':
      return InsurancePlanCost.empty();
    case 'insuranceplan_cost':
      return InsurancePlanCost.empty();
    case 'invoice':
      return Invoice.empty();
    case 'invoiceparticipant':
      return InvoiceParticipant.empty();
    case 'invoice_participant':
      return InvoiceParticipant.empty();
    case 'invoicelineitem':
      return InvoiceLineItem.empty();
    case 'invoice_lineitem':
      return InvoiceLineItem.empty();
    case 'invoicepricecomponent':
      return InvoicePriceComponent.empty();
    case 'invoice_pricecomponent':
      return InvoicePriceComponent.empty();
    case 'library':
      return Library.empty();
    case 'linkage':
      return Linkage.empty();
    case 'linkageitem':
      return LinkageItem.empty();
    case 'linkage_item':
      return LinkageItem.empty();
    case 'fhirlist':
      return FhirList.empty();
    case 'list':
      return FhirList.empty();
    case 'listentry':
      return ListEntry.empty();
    case 'list_entry':
      return ListEntry.empty();
    case 'location':
      return Location.empty();
    case 'locationposition':
      return LocationPosition.empty();
    case 'location_position':
      return LocationPosition.empty();
    case 'locationhoursofoperation':
      return LocationHoursOfOperation.empty();
    case 'location_hoursofoperation':
      return LocationHoursOfOperation.empty();
    case 'manufactureditemdefinition':
      return ManufacturedItemDefinition.empty();
    case 'manufactureditemdefinitionproperty':
      return ManufacturedItemDefinitionProperty.empty();
    case 'manufactureditemdefinition_property':
      return ManufacturedItemDefinitionProperty.empty();
    case 'measure':
      return Measure.empty();
    case 'measuregroup':
      return MeasureGroup.empty();
    case 'measure_group':
      return MeasureGroup.empty();
    case 'measurepopulation':
      return MeasurePopulation.empty();
    case 'measure_population':
      return MeasurePopulation.empty();
    case 'measurestratifier':
      return MeasureStratifier.empty();
    case 'measure_stratifier':
      return MeasureStratifier.empty();
    case 'measurecomponent':
      return MeasureComponent.empty();
    case 'measure_component':
      return MeasureComponent.empty();
    case 'measuresupplementaldata':
      return MeasureSupplementalData.empty();
    case 'measure_supplementaldata':
      return MeasureSupplementalData.empty();
    case 'measurereport':
      return MeasureReport.empty();
    case 'measurereportgroup':
      return MeasureReportGroup.empty();
    case 'measurereport_group':
      return MeasureReportGroup.empty();
    case 'measurereportpopulation':
      return MeasureReportPopulation.empty();
    case 'measurereport_population':
      return MeasureReportPopulation.empty();
    case 'measurereportstratifier':
      return MeasureReportStratifier.empty();
    case 'measurereport_stratifier':
      return MeasureReportStratifier.empty();
    case 'measurereportstratum':
      return MeasureReportStratum.empty();
    case 'measurereport_stratum':
      return MeasureReportStratum.empty();
    case 'measurereportcomponent':
      return MeasureReportComponent.empty();
    case 'measurereport_component':
      return MeasureReportComponent.empty();
    case 'measurereportpopulation1':
      return MeasureReportPopulation1.empty();
    case 'measurereport_population1':
      return MeasureReportPopulation1.empty();
    case 'media':
      return Media.empty();
    case 'medication':
      return Medication.empty();
    case 'medicationingredient':
      return MedicationIngredient.empty();
    case 'medication_ingredient':
      return MedicationIngredient.empty();
    case 'medicationbatch':
      return MedicationBatch.empty();
    case 'medication_batch':
      return MedicationBatch.empty();
    case 'medicationadministration':
      return MedicationAdministration.empty();
    case 'medicationadministrationperformer':
      return MedicationAdministrationPerformer.empty();
    case 'medicationadministration_performer':
      return MedicationAdministrationPerformer.empty();
    case 'medicationadministrationdosage':
      return MedicationAdministrationDosage.empty();
    case 'medicationadministration_dosage':
      return MedicationAdministrationDosage.empty();
    case 'medicationdispense':
      return MedicationDispense.empty();
    case 'medicationdispenseperformer':
      return MedicationDispensePerformer.empty();
    case 'medicationdispense_performer':
      return MedicationDispensePerformer.empty();
    case 'medicationdispensesubstitution':
      return MedicationDispenseSubstitution.empty();
    case 'medicationdispense_substitution':
      return MedicationDispenseSubstitution.empty();
    case 'medicationknowledge':
      return MedicationKnowledge.empty();
    case 'medicationknowledgerelatedmedicationknowledge':
      return MedicationKnowledgeRelatedMedicationKnowledge.empty();
    case 'medicationknowledge_relatedmedicationknowledge':
      return MedicationKnowledgeRelatedMedicationKnowledge.empty();
    case 'medicationknowledgemonograph':
      return MedicationKnowledgeMonograph.empty();
    case 'medicationknowledge_monograph':
      return MedicationKnowledgeMonograph.empty();
    case 'medicationknowledgeingredient':
      return MedicationKnowledgeIngredient.empty();
    case 'medicationknowledge_ingredient':
      return MedicationKnowledgeIngredient.empty();
    case 'medicationknowledgecost':
      return MedicationKnowledgeCost.empty();
    case 'medicationknowledge_cost':
      return MedicationKnowledgeCost.empty();
    case 'medicationknowledgemonitoringprogram':
      return MedicationKnowledgeMonitoringProgram.empty();
    case 'medicationknowledge_monitoringprogram':
      return MedicationKnowledgeMonitoringProgram.empty();
    case 'medicationknowledgeadministrationguidelines':
      return MedicationKnowledgeAdministrationGuidelines.empty();
    case 'medicationknowledge_administrationguidelines':
      return MedicationKnowledgeAdministrationGuidelines.empty();
    case 'medicationknowledgedosage':
      return MedicationKnowledgeDosage.empty();
    case 'medicationknowledge_dosage':
      return MedicationKnowledgeDosage.empty();
    case 'medicationknowledgepatientcharacteristics':
      return MedicationKnowledgePatientCharacteristics.empty();
    case 'medicationknowledge_patientcharacteristics':
      return MedicationKnowledgePatientCharacteristics.empty();
    case 'medicationknowledgemedicineclassification':
      return MedicationKnowledgeMedicineClassification.empty();
    case 'medicationknowledge_medicineclassification':
      return MedicationKnowledgeMedicineClassification.empty();
    case 'medicationknowledgepackaging':
      return MedicationKnowledgePackaging.empty();
    case 'medicationknowledge_packaging':
      return MedicationKnowledgePackaging.empty();
    case 'medicationknowledgedrugcharacteristic':
      return MedicationKnowledgeDrugCharacteristic.empty();
    case 'medicationknowledge_drugcharacteristic':
      return MedicationKnowledgeDrugCharacteristic.empty();
    case 'medicationknowledgeregulatory':
      return MedicationKnowledgeRegulatory.empty();
    case 'medicationknowledge_regulatory':
      return MedicationKnowledgeRegulatory.empty();
    case 'medicationknowledgesubstitution':
      return MedicationKnowledgeSubstitution.empty();
    case 'medicationknowledge_substitution':
      return MedicationKnowledgeSubstitution.empty();
    case 'medicationknowledgeschedule':
      return MedicationKnowledgeSchedule.empty();
    case 'medicationknowledge_schedule':
      return MedicationKnowledgeSchedule.empty();
    case 'medicationknowledgemaxdispense':
      return MedicationKnowledgeMaxDispense.empty();
    case 'medicationknowledge_maxdispense':
      return MedicationKnowledgeMaxDispense.empty();
    case 'medicationknowledgekinetics':
      return MedicationKnowledgeKinetics.empty();
    case 'medicationknowledge_kinetics':
      return MedicationKnowledgeKinetics.empty();
    case 'medicationrequest':
      return MedicationRequest.empty();
    case 'medicationrequestdispenserequest':
      return MedicationRequestDispenseRequest.empty();
    case 'medicationrequest_dispenserequest':
      return MedicationRequestDispenseRequest.empty();
    case 'medicationrequestinitialfill':
      return MedicationRequestInitialFill.empty();
    case 'medicationrequest_initialfill':
      return MedicationRequestInitialFill.empty();
    case 'medicationrequestsubstitution':
      return MedicationRequestSubstitution.empty();
    case 'medicationrequest_substitution':
      return MedicationRequestSubstitution.empty();
    case 'medicationstatement':
      return MedicationStatement.empty();
    case 'medicinalproductdefinition':
      return MedicinalProductDefinition.empty();
    case 'medicinalproductdefinitioncontact':
      return MedicinalProductDefinitionContact.empty();
    case 'medicinalproductdefinition_contact':
      return MedicinalProductDefinitionContact.empty();
    case 'medicinalproductdefinitionname':
      return MedicinalProductDefinitionName.empty();
    case 'medicinalproductdefinition_name':
      return MedicinalProductDefinitionName.empty();
    case 'medicinalproductdefinitionnamepart':
      return MedicinalProductDefinitionNamePart.empty();
    case 'medicinalproductdefinition_namepart':
      return MedicinalProductDefinitionNamePart.empty();
    case 'medicinalproductdefinitioncountrylanguage':
      return MedicinalProductDefinitionCountryLanguage.empty();
    case 'medicinalproductdefinition_countrylanguage':
      return MedicinalProductDefinitionCountryLanguage.empty();
    case 'medicinalproductdefinitioncrossreference':
      return MedicinalProductDefinitionCrossReference.empty();
    case 'medicinalproductdefinition_crossreference':
      return MedicinalProductDefinitionCrossReference.empty();
    case 'medicinalproductdefinitionoperation':
      return MedicinalProductDefinitionOperation.empty();
    case 'medicinalproductdefinition_operation':
      return MedicinalProductDefinitionOperation.empty();
    case 'medicinalproductdefinitioncharacteristic':
      return MedicinalProductDefinitionCharacteristic.empty();
    case 'medicinalproductdefinition_characteristic':
      return MedicinalProductDefinitionCharacteristic.empty();
    case 'messagedefinition':
      return MessageDefinition.empty();
    case 'messagedefinitionfocus':
      return MessageDefinitionFocus.empty();
    case 'messagedefinition_focus':
      return MessageDefinitionFocus.empty();
    case 'messagedefinitionallowedresponse':
      return MessageDefinitionAllowedResponse.empty();
    case 'messagedefinition_allowedresponse':
      return MessageDefinitionAllowedResponse.empty();
    case 'messageheader':
      return MessageHeader.empty();
    case 'messageheaderdestination':
      return MessageHeaderDestination.empty();
    case 'messageheader_destination':
      return MessageHeaderDestination.empty();
    case 'messageheadersource':
      return MessageHeaderSource.empty();
    case 'messageheader_source':
      return MessageHeaderSource.empty();
    case 'messageheaderresponse':
      return MessageHeaderResponse.empty();
    case 'messageheader_response':
      return MessageHeaderResponse.empty();
    case 'molecularsequence':
      return MolecularSequence.empty();
    case 'molecularsequencereferenceseq':
      return MolecularSequenceReferenceSeq.empty();
    case 'molecularsequence_referenceseq':
      return MolecularSequenceReferenceSeq.empty();
    case 'molecularsequencevariant':
      return MolecularSequenceVariant.empty();
    case 'molecularsequence_variant':
      return MolecularSequenceVariant.empty();
    case 'molecularsequencequality':
      return MolecularSequenceQuality.empty();
    case 'molecularsequence_quality':
      return MolecularSequenceQuality.empty();
    case 'molecularsequenceroc':
      return MolecularSequenceRoc.empty();
    case 'molecularsequence_roc':
      return MolecularSequenceRoc.empty();
    case 'molecularsequencerepository':
      return MolecularSequenceRepository.empty();
    case 'molecularsequence_repository':
      return MolecularSequenceRepository.empty();
    case 'molecularsequencestructurevariant':
      return MolecularSequenceStructureVariant.empty();
    case 'molecularsequence_structurevariant':
      return MolecularSequenceStructureVariant.empty();
    case 'molecularsequenceouter':
      return MolecularSequenceOuter.empty();
    case 'molecularsequence_outer':
      return MolecularSequenceOuter.empty();
    case 'molecularsequenceinner':
      return MolecularSequenceInner.empty();
    case 'molecularsequence_inner':
      return MolecularSequenceInner.empty();
    case 'namingsystem':
      return NamingSystem.empty();
    case 'namingsystemuniqueid':
      return NamingSystemUniqueId.empty();
    case 'namingsystem_uniqueid':
      return NamingSystemUniqueId.empty();
    case 'nutritionorder':
      return NutritionOrder.empty();
    case 'nutritionorderoraldiet':
      return NutritionOrderOralDiet.empty();
    case 'nutritionorder_oraldiet':
      return NutritionOrderOralDiet.empty();
    case 'nutritionordernutrient':
      return NutritionOrderNutrient.empty();
    case 'nutritionorder_nutrient':
      return NutritionOrderNutrient.empty();
    case 'nutritionordertexture':
      return NutritionOrderTexture.empty();
    case 'nutritionorder_texture':
      return NutritionOrderTexture.empty();
    case 'nutritionordersupplement':
      return NutritionOrderSupplement.empty();
    case 'nutritionorder_supplement':
      return NutritionOrderSupplement.empty();
    case 'nutritionorderenteralformula':
      return NutritionOrderEnteralFormula.empty();
    case 'nutritionorder_enteralformula':
      return NutritionOrderEnteralFormula.empty();
    case 'nutritionorderadministration':
      return NutritionOrderAdministration.empty();
    case 'nutritionorder_administration':
      return NutritionOrderAdministration.empty();
    case 'nutritionproduct':
      return NutritionProduct.empty();
    case 'nutritionproductnutrient':
      return NutritionProductNutrient.empty();
    case 'nutritionproduct_nutrient':
      return NutritionProductNutrient.empty();
    case 'nutritionproductingredient':
      return NutritionProductIngredient.empty();
    case 'nutritionproduct_ingredient':
      return NutritionProductIngredient.empty();
    case 'nutritionproductproductcharacteristic':
      return NutritionProductProductCharacteristic.empty();
    case 'nutritionproduct_productcharacteristic':
      return NutritionProductProductCharacteristic.empty();
    case 'nutritionproductinstance':
      return NutritionProductInstance.empty();
    case 'nutritionproduct_instance':
      return NutritionProductInstance.empty();
    case 'observation':
      return Observation.empty();
    case 'observationreferencerange':
      return ObservationReferenceRange.empty();
    case 'observation_referencerange':
      return ObservationReferenceRange.empty();
    case 'observationcomponent':
      return ObservationComponent.empty();
    case 'observation_component':
      return ObservationComponent.empty();
    case 'observationdefinition':
      return ObservationDefinition.empty();
    case 'observationdefinitionquantitativedetails':
      return ObservationDefinitionQuantitativeDetails.empty();
    case 'observationdefinition_quantitativedetails':
      return ObservationDefinitionQuantitativeDetails.empty();
    case 'observationdefinitionqualifiedinterval':
      return ObservationDefinitionQualifiedInterval.empty();
    case 'observationdefinition_qualifiedinterval':
      return ObservationDefinitionQualifiedInterval.empty();
    case 'operationdefinition':
      return OperationDefinition.empty();
    case 'operationdefinitionparameter':
      return OperationDefinitionParameter.empty();
    case 'operationdefinition_parameter':
      return OperationDefinitionParameter.empty();
    case 'operationdefinitionbinding':
      return OperationDefinitionBinding.empty();
    case 'operationdefinition_binding':
      return OperationDefinitionBinding.empty();
    case 'operationdefinitionreferencedfrom':
      return OperationDefinitionReferencedFrom.empty();
    case 'operationdefinition_referencedfrom':
      return OperationDefinitionReferencedFrom.empty();
    case 'operationdefinitionoverload':
      return OperationDefinitionOverload.empty();
    case 'operationdefinition_overload':
      return OperationDefinitionOverload.empty();
    case 'operationoutcome':
      return OperationOutcome.empty();
    case 'operationoutcomeissue':
      return OperationOutcomeIssue.empty();
    case 'operationoutcome_issue':
      return OperationOutcomeIssue.empty();
    case 'organization':
      return Organization.empty();
    case 'organizationcontact':
      return OrganizationContact.empty();
    case 'organization_contact':
      return OrganizationContact.empty();
    case 'organizationaffiliation':
      return OrganizationAffiliation.empty();
    case 'packagedproductdefinition':
      return PackagedProductDefinition.empty();
    case 'packagedproductdefinitionlegalstatusofsupply':
      return PackagedProductDefinitionLegalStatusOfSupply.empty();
    case 'packagedproductdefinition_legalstatusofsupply':
      return PackagedProductDefinitionLegalStatusOfSupply.empty();
    case 'packagedproductdefinitionpackage':
      return PackagedProductDefinitionPackage.empty();
    case 'packagedproductdefinition_package':
      return PackagedProductDefinitionPackage.empty();
    case 'packagedproductdefinitionshelflifestorage':
      return PackagedProductDefinitionShelfLifeStorage.empty();
    case 'packagedproductdefinition_shelflifestorage':
      return PackagedProductDefinitionShelfLifeStorage.empty();
    case 'packagedproductdefinitionproperty':
      return PackagedProductDefinitionProperty.empty();
    case 'packagedproductdefinition_property':
      return PackagedProductDefinitionProperty.empty();
    case 'packagedproductdefinitioncontaineditem':
      return PackagedProductDefinitionContainedItem.empty();
    case 'packagedproductdefinition_containeditem':
      return PackagedProductDefinitionContainedItem.empty();
    case 'parameters':
      return Parameters.empty();
    case 'parametersparameter':
      return ParametersParameter.empty();
    case 'parameters_parameter':
      return ParametersParameter.empty();
    case 'patient':
      return Patient.empty();
    case 'patientcontact':
      return PatientContact.empty();
    case 'patient_contact':
      return PatientContact.empty();
    case 'patientcommunication':
      return PatientCommunication.empty();
    case 'patient_communication':
      return PatientCommunication.empty();
    case 'patientlink':
      return PatientLink.empty();
    case 'patient_link':
      return PatientLink.empty();
    case 'paymentnotice':
      return PaymentNotice.empty();
    case 'paymentreconciliation':
      return PaymentReconciliation.empty();
    case 'paymentreconciliationdetail':
      return PaymentReconciliationDetail.empty();
    case 'paymentreconciliation_detail':
      return PaymentReconciliationDetail.empty();
    case 'paymentreconciliationprocessnote':
      return PaymentReconciliationProcessNote.empty();
    case 'paymentreconciliation_processnote':
      return PaymentReconciliationProcessNote.empty();
    case 'person':
      return Person.empty();
    case 'personlink':
      return PersonLink.empty();
    case 'person_link':
      return PersonLink.empty();
    case 'plandefinition':
      return PlanDefinition.empty();
    case 'plandefinitiongoal':
      return PlanDefinitionGoal.empty();
    case 'plandefinition_goal':
      return PlanDefinitionGoal.empty();
    case 'plandefinitiontarget':
      return PlanDefinitionTarget.empty();
    case 'plandefinition_target':
      return PlanDefinitionTarget.empty();
    case 'plandefinitionaction':
      return PlanDefinitionAction.empty();
    case 'plandefinition_action':
      return PlanDefinitionAction.empty();
    case 'plandefinitioncondition':
      return PlanDefinitionCondition.empty();
    case 'plandefinition_condition':
      return PlanDefinitionCondition.empty();
    case 'plandefinitionrelatedaction':
      return PlanDefinitionRelatedAction.empty();
    case 'plandefinition_relatedaction':
      return PlanDefinitionRelatedAction.empty();
    case 'plandefinitionparticipant':
      return PlanDefinitionParticipant.empty();
    case 'plandefinition_participant':
      return PlanDefinitionParticipant.empty();
    case 'plandefinitiondynamicvalue':
      return PlanDefinitionDynamicValue.empty();
    case 'plandefinition_dynamicvalue':
      return PlanDefinitionDynamicValue.empty();
    case 'practitioner':
      return Practitioner.empty();
    case 'practitionerqualification':
      return PractitionerQualification.empty();
    case 'practitioner_qualification':
      return PractitionerQualification.empty();
    case 'practitionerrole':
      return PractitionerRole.empty();
    case 'practitionerroleavailabletime':
      return PractitionerRoleAvailableTime.empty();
    case 'practitionerrole_availabletime':
      return PractitionerRoleAvailableTime.empty();
    case 'practitionerrolenotavailable':
      return PractitionerRoleNotAvailable.empty();
    case 'practitionerrole_notavailable':
      return PractitionerRoleNotAvailable.empty();
    case 'procedure':
      return Procedure.empty();
    case 'procedureperformer':
      return ProcedurePerformer.empty();
    case 'procedure_performer':
      return ProcedurePerformer.empty();
    case 'procedurefocaldevice':
      return ProcedureFocalDevice.empty();
    case 'procedure_focaldevice':
      return ProcedureFocalDevice.empty();
    case 'provenance':
      return Provenance.empty();
    case 'provenanceagent':
      return ProvenanceAgent.empty();
    case 'provenance_agent':
      return ProvenanceAgent.empty();
    case 'provenanceentity':
      return ProvenanceEntity.empty();
    case 'provenance_entity':
      return ProvenanceEntity.empty();
    case 'questionnaire':
      return Questionnaire.empty();
    case 'questionnaireitem':
      return QuestionnaireItem.empty();
    case 'questionnaire_item':
      return QuestionnaireItem.empty();
    case 'questionnaireenablewhen':
      return QuestionnaireEnableWhen.empty();
    case 'questionnaire_enablewhen':
      return QuestionnaireEnableWhen.empty();
    case 'questionnaireansweroption':
      return QuestionnaireAnswerOption.empty();
    case 'questionnaire_answeroption':
      return QuestionnaireAnswerOption.empty();
    case 'questionnaireinitial':
      return QuestionnaireInitial.empty();
    case 'questionnaire_initial':
      return QuestionnaireInitial.empty();
    case 'questionnaireresponse':
      return QuestionnaireResponse.empty();
    case 'questionnaireresponseitem':
      return QuestionnaireResponseItem.empty();
    case 'questionnaireresponse_item':
      return QuestionnaireResponseItem.empty();
    case 'questionnaireresponseanswer':
      return QuestionnaireResponseAnswer.empty();
    case 'questionnaireresponse_answer':
      return QuestionnaireResponseAnswer.empty();
    case 'regulatedauthorization':
      return RegulatedAuthorization.empty();
    case 'regulatedauthorizationcase':
      return RegulatedAuthorizationCase.empty();
    case 'regulatedauthorization_case':
      return RegulatedAuthorizationCase.empty();
    case 'relatedperson':
      return RelatedPerson.empty();
    case 'relatedpersoncommunication':
      return RelatedPersonCommunication.empty();
    case 'relatedperson_communication':
      return RelatedPersonCommunication.empty();
    case 'requestgroup':
      return RequestGroup.empty();
    case 'requestgroupaction':
      return RequestGroupAction.empty();
    case 'requestgroup_action':
      return RequestGroupAction.empty();
    case 'requestgroupcondition':
      return RequestGroupCondition.empty();
    case 'requestgroup_condition':
      return RequestGroupCondition.empty();
    case 'requestgrouprelatedaction':
      return RequestGroupRelatedAction.empty();
    case 'requestgroup_relatedaction':
      return RequestGroupRelatedAction.empty();
    case 'researchdefinition':
      return ResearchDefinition.empty();
    case 'researchelementdefinition':
      return ResearchElementDefinition.empty();
    case 'researchelementdefinitioncharacteristic':
      return ResearchElementDefinitionCharacteristic.empty();
    case 'researchelementdefinition_characteristic':
      return ResearchElementDefinitionCharacteristic.empty();
    case 'researchstudy':
      return ResearchStudy.empty();
    case 'researchstudyarm':
      return ResearchStudyArm.empty();
    case 'researchstudy_arm':
      return ResearchStudyArm.empty();
    case 'researchstudyobjective':
      return ResearchStudyObjective.empty();
    case 'researchstudy_objective':
      return ResearchStudyObjective.empty();
    case 'researchsubject':
      return ResearchSubject.empty();
    case 'riskassessment':
      return RiskAssessment.empty();
    case 'riskassessmentprediction':
      return RiskAssessmentPrediction.empty();
    case 'riskassessment_prediction':
      return RiskAssessmentPrediction.empty();
    case 'schedule':
      return Schedule.empty();
    case 'searchparameter':
      return SearchParameter.empty();
    case 'searchparametercomponent':
      return SearchParameterComponent.empty();
    case 'searchparameter_component':
      return SearchParameterComponent.empty();
    case 'servicerequest':
      return ServiceRequest.empty();
    case 'slot':
      return Slot.empty();
    case 'specimen':
      return Specimen.empty();
    case 'specimencollection':
      return SpecimenCollection.empty();
    case 'specimen_collection':
      return SpecimenCollection.empty();
    case 'specimenprocessing':
      return SpecimenProcessing.empty();
    case 'specimen_processing':
      return SpecimenProcessing.empty();
    case 'specimencontainer':
      return SpecimenContainer.empty();
    case 'specimen_container':
      return SpecimenContainer.empty();
    case 'specimendefinition':
      return SpecimenDefinition.empty();
    case 'specimendefinitiontypetested':
      return SpecimenDefinitionTypeTested.empty();
    case 'specimendefinition_typetested':
      return SpecimenDefinitionTypeTested.empty();
    case 'specimendefinitioncontainer':
      return SpecimenDefinitionContainer.empty();
    case 'specimendefinition_container':
      return SpecimenDefinitionContainer.empty();
    case 'specimendefinitionadditive':
      return SpecimenDefinitionAdditive.empty();
    case 'specimendefinition_additive':
      return SpecimenDefinitionAdditive.empty();
    case 'specimendefinitionhandling':
      return SpecimenDefinitionHandling.empty();
    case 'specimendefinition_handling':
      return SpecimenDefinitionHandling.empty();
    case 'structuredefinition':
      return StructureDefinition.empty();
    case 'structuredefinitionmapping':
      return StructureDefinitionMapping.empty();
    case 'structuredefinition_mapping':
      return StructureDefinitionMapping.empty();
    case 'structuredefinitioncontext':
      return StructureDefinitionContext.empty();
    case 'structuredefinition_context':
      return StructureDefinitionContext.empty();
    case 'structuredefinitionsnapshot':
      return StructureDefinitionSnapshot.empty();
    case 'structuredefinition_snapshot':
      return StructureDefinitionSnapshot.empty();
    case 'structuredefinitiondifferential':
      return StructureDefinitionDifferential.empty();
    case 'structuredefinition_differential':
      return StructureDefinitionDifferential.empty();
    case 'structuremap':
      return StructureMap.empty();
    case 'structuremapstructure':
      return StructureMapStructure.empty();
    case 'structuremap_structure':
      return StructureMapStructure.empty();
    case 'structuremapgroup':
      return StructureMapGroup.empty();
    case 'structuremap_group':
      return StructureMapGroup.empty();
    case 'structuremapinput':
      return StructureMapInput.empty();
    case 'structuremap_input':
      return StructureMapInput.empty();
    case 'structuremaprule':
      return StructureMapRule.empty();
    case 'structuremap_rule':
      return StructureMapRule.empty();
    case 'structuremapsource':
      return StructureMapSource.empty();
    case 'structuremap_source':
      return StructureMapSource.empty();
    case 'structuremaptarget':
      return StructureMapTarget.empty();
    case 'structuremap_target':
      return StructureMapTarget.empty();
    case 'structuremapparameter':
      return StructureMapParameter.empty();
    case 'structuremap_parameter':
      return StructureMapParameter.empty();
    case 'structuremapdependent':
      return StructureMapDependent.empty();
    case 'structuremap_dependent':
      return StructureMapDependent.empty();
    case 'subscription':
      return Subscription.empty();
    case 'subscriptionchannel':
      return SubscriptionChannel.empty();
    case 'subscription_channel':
      return SubscriptionChannel.empty();
    case 'subscriptionstatus':
      return SubscriptionStatus.empty();
    case 'subscriptionstatusnotificationevent':
      return SubscriptionStatusNotificationEvent.empty();
    case 'subscriptionstatus_notificationevent':
      return SubscriptionStatusNotificationEvent.empty();
    case 'subscriptiontopic':
      return SubscriptionTopic.empty();
    case 'subscriptiontopicresourcetrigger':
      return SubscriptionTopicResourceTrigger.empty();
    case 'subscriptiontopic_resourcetrigger':
      return SubscriptionTopicResourceTrigger.empty();
    case 'subscriptiontopicquerycriteria':
      return SubscriptionTopicQueryCriteria.empty();
    case 'subscriptiontopic_querycriteria':
      return SubscriptionTopicQueryCriteria.empty();
    case 'subscriptiontopiceventtrigger':
      return SubscriptionTopicEventTrigger.empty();
    case 'subscriptiontopic_eventtrigger':
      return SubscriptionTopicEventTrigger.empty();
    case 'subscriptiontopiccanfilterby':
      return SubscriptionTopicCanFilterBy.empty();
    case 'subscriptiontopic_canfilterby':
      return SubscriptionTopicCanFilterBy.empty();
    case 'subscriptiontopicnotificationshape':
      return SubscriptionTopicNotificationShape.empty();
    case 'subscriptiontopic_notificationshape':
      return SubscriptionTopicNotificationShape.empty();
    case 'substance':
      return Substance.empty();
    case 'substanceinstance':
      return SubstanceInstance.empty();
    case 'substance_instance':
      return SubstanceInstance.empty();
    case 'substanceingredient':
      return SubstanceIngredient.empty();
    case 'substance_ingredient':
      return SubstanceIngredient.empty();
    case 'substancedefinition':
      return SubstanceDefinition.empty();
    case 'substancedefinitionmoiety':
      return SubstanceDefinitionMoiety.empty();
    case 'substancedefinition_moiety':
      return SubstanceDefinitionMoiety.empty();
    case 'substancedefinitionproperty':
      return SubstanceDefinitionProperty.empty();
    case 'substancedefinition_property':
      return SubstanceDefinitionProperty.empty();
    case 'substancedefinitionmolecularweight':
      return SubstanceDefinitionMolecularWeight.empty();
    case 'substancedefinition_molecularweight':
      return SubstanceDefinitionMolecularWeight.empty();
    case 'substancedefinitionstructure':
      return SubstanceDefinitionStructure.empty();
    case 'substancedefinition_structure':
      return SubstanceDefinitionStructure.empty();
    case 'substancedefinitionrepresentation':
      return SubstanceDefinitionRepresentation.empty();
    case 'substancedefinition_representation':
      return SubstanceDefinitionRepresentation.empty();
    case 'substancedefinitioncode':
      return SubstanceDefinitionCode.empty();
    case 'substancedefinition_code':
      return SubstanceDefinitionCode.empty();
    case 'substancedefinitionname':
      return SubstanceDefinitionName.empty();
    case 'substancedefinition_name':
      return SubstanceDefinitionName.empty();
    case 'substancedefinitionofficial':
      return SubstanceDefinitionOfficial.empty();
    case 'substancedefinition_official':
      return SubstanceDefinitionOfficial.empty();
    case 'substancedefinitionrelationship':
      return SubstanceDefinitionRelationship.empty();
    case 'substancedefinition_relationship':
      return SubstanceDefinitionRelationship.empty();
    case 'substancedefinitionsourcematerial':
      return SubstanceDefinitionSourceMaterial.empty();
    case 'substancedefinition_sourcematerial':
      return SubstanceDefinitionSourceMaterial.empty();
    case 'supplydelivery':
      return SupplyDelivery.empty();
    case 'supplydeliverysupplieditem':
      return SupplyDeliverySuppliedItem.empty();
    case 'supplydelivery_supplieditem':
      return SupplyDeliverySuppliedItem.empty();
    case 'supplyrequest':
      return SupplyRequest.empty();
    case 'supplyrequestparameter':
      return SupplyRequestParameter.empty();
    case 'supplyrequest_parameter':
      return SupplyRequestParameter.empty();
    case 'task':
      return Task.empty();
    case 'taskrestriction':
      return TaskRestriction.empty();
    case 'task_restriction':
      return TaskRestriction.empty();
    case 'taskinput':
      return TaskInput.empty();
    case 'task_input':
      return TaskInput.empty();
    case 'taskoutput':
      return TaskOutput.empty();
    case 'task_output':
      return TaskOutput.empty();
    case 'terminologycapabilities':
      return TerminologyCapabilities.empty();
    case 'terminologycapabilitiessoftware':
      return TerminologyCapabilitiesSoftware.empty();
    case 'terminologycapabilities_software':
      return TerminologyCapabilitiesSoftware.empty();
    case 'terminologycapabilitiesimplementation':
      return TerminologyCapabilitiesImplementation.empty();
    case 'terminologycapabilities_implementation':
      return TerminologyCapabilitiesImplementation.empty();
    case 'terminologycapabilitiescodesystem':
      return TerminologyCapabilitiesCodeSystem.empty();
    case 'terminologycapabilities_codesystem':
      return TerminologyCapabilitiesCodeSystem.empty();
    case 'terminologycapabilitiesversion':
      return TerminologyCapabilitiesVersion.empty();
    case 'terminologycapabilities_version':
      return TerminologyCapabilitiesVersion.empty();
    case 'terminologycapabilitiesfilter':
      return TerminologyCapabilitiesFilter.empty();
    case 'terminologycapabilities_filter':
      return TerminologyCapabilitiesFilter.empty();
    case 'terminologycapabilitiesexpansion':
      return TerminologyCapabilitiesExpansion.empty();
    case 'terminologycapabilities_expansion':
      return TerminologyCapabilitiesExpansion.empty();
    case 'terminologycapabilitiesparameter':
      return TerminologyCapabilitiesParameter.empty();
    case 'terminologycapabilities_parameter':
      return TerminologyCapabilitiesParameter.empty();
    case 'terminologycapabilitiesvalidatecode':
      return TerminologyCapabilitiesValidateCode.empty();
    case 'terminologycapabilities_validatecode':
      return TerminologyCapabilitiesValidateCode.empty();
    case 'terminologycapabilitiestranslation':
      return TerminologyCapabilitiesTranslation.empty();
    case 'terminologycapabilities_translation':
      return TerminologyCapabilitiesTranslation.empty();
    case 'terminologycapabilitiesclosure':
      return TerminologyCapabilitiesClosure.empty();
    case 'terminologycapabilities_closure':
      return TerminologyCapabilitiesClosure.empty();
    case 'testreport':
      return TestReport.empty();
    case 'testreportparticipant':
      return TestReportParticipant.empty();
    case 'testreport_participant':
      return TestReportParticipant.empty();
    case 'testreportsetup':
      return TestReportSetup.empty();
    case 'testreport_setup':
      return TestReportSetup.empty();
    case 'testreportaction':
      return TestReportAction.empty();
    case 'testreport_action':
      return TestReportAction.empty();
    case 'testreportoperation':
      return TestReportOperation.empty();
    case 'testreport_operation':
      return TestReportOperation.empty();
    case 'testreportassert':
      return TestReportAssert.empty();
    case 'testreport_assert':
      return TestReportAssert.empty();
    case 'testreporttest':
      return TestReportTest.empty();
    case 'testreport_test':
      return TestReportTest.empty();
    case 'testreportaction1':
      return TestReportAction1.empty();
    case 'testreport_action1':
      return TestReportAction1.empty();
    case 'testreportteardown':
      return TestReportTeardown.empty();
    case 'testreport_teardown':
      return TestReportTeardown.empty();
    case 'testreportaction2':
      return TestReportAction2.empty();
    case 'testreport_action2':
      return TestReportAction2.empty();
    case 'testscript':
      return TestScript.empty();
    case 'testscriptorigin':
      return TestScriptOrigin.empty();
    case 'testscript_origin':
      return TestScriptOrigin.empty();
    case 'testscriptdestination':
      return TestScriptDestination.empty();
    case 'testscript_destination':
      return TestScriptDestination.empty();
    case 'testscriptmetadata':
      return TestScriptMetadata.empty();
    case 'testscript_metadata':
      return TestScriptMetadata.empty();
    case 'testscriptlink':
      return TestScriptLink.empty();
    case 'testscript_link':
      return TestScriptLink.empty();
    case 'testscriptcapability':
      return TestScriptCapability.empty();
    case 'testscript_capability':
      return TestScriptCapability.empty();
    case 'testscriptfixture':
      return TestScriptFixture.empty();
    case 'testscript_fixture':
      return TestScriptFixture.empty();
    case 'testscriptvariable':
      return TestScriptVariable.empty();
    case 'testscript_variable':
      return TestScriptVariable.empty();
    case 'testscriptsetup':
      return TestScriptSetup.empty();
    case 'testscript_setup':
      return TestScriptSetup.empty();
    case 'testscriptaction':
      return TestScriptAction.empty();
    case 'testscript_action':
      return TestScriptAction.empty();
    case 'testscriptoperation':
      return TestScriptOperation.empty();
    case 'testscript_operation':
      return TestScriptOperation.empty();
    case 'testscriptrequestheader':
      return TestScriptRequestHeader.empty();
    case 'testscript_requestheader':
      return TestScriptRequestHeader.empty();
    case 'testscriptassert':
      return TestScriptAssert.empty();
    case 'testscript_assert':
      return TestScriptAssert.empty();
    case 'testscripttest':
      return TestScriptTest.empty();
    case 'testscript_test':
      return TestScriptTest.empty();
    case 'testscriptaction1':
      return TestScriptAction1.empty();
    case 'testscript_action1':
      return TestScriptAction1.empty();
    case 'testscriptteardown':
      return TestScriptTeardown.empty();
    case 'testscript_teardown':
      return TestScriptTeardown.empty();
    case 'testscriptaction2':
      return TestScriptAction2.empty();
    case 'testscript_action2':
      return TestScriptAction2.empty();
    case 'valueset':
      return ValueSet.empty();
    case 'valuesetcompose':
      return ValueSetCompose.empty();
    case 'valueset_compose':
      return ValueSetCompose.empty();
    case 'valuesetinclude':
      return ValueSetInclude.empty();
    case 'valueset_include':
      return ValueSetInclude.empty();
    case 'valuesetconcept':
      return ValueSetConcept.empty();
    case 'valueset_concept':
      return ValueSetConcept.empty();
    case 'valuesetdesignation':
      return ValueSetDesignation.empty();
    case 'valueset_designation':
      return ValueSetDesignation.empty();
    case 'valuesetfilter':
      return ValueSetFilter.empty();
    case 'valueset_filter':
      return ValueSetFilter.empty();
    case 'valuesetexpansion':
      return ValueSetExpansion.empty();
    case 'valueset_expansion':
      return ValueSetExpansion.empty();
    case 'valuesetparameter':
      return ValueSetParameter.empty();
    case 'valueset_parameter':
      return ValueSetParameter.empty();
    case 'valuesetcontains':
      return ValueSetContains.empty();
    case 'valueset_contains':
      return ValueSetContains.empty();
    case 'verificationresult':
      return VerificationResult.empty();
    case 'verificationresultprimarysource':
      return VerificationResultPrimarySource.empty();
    case 'verificationresult_primarysource':
      return VerificationResultPrimarySource.empty();
    case 'verificationresultattestation':
      return VerificationResultAttestation.empty();
    case 'verificationresult_attestation':
      return VerificationResultAttestation.empty();
    case 'verificationresultvalidator':
      return VerificationResultValidator.empty();
    case 'verificationresult_validator':
      return VerificationResultValidator.empty();
    case 'visionprescription':
      return VisionPrescription.empty();
    case 'visionprescriptionlensspecification':
      return VisionPrescriptionLensSpecification.empty();
    case 'visionprescription_lensspecification':
      return VisionPrescriptionLensSpecification.empty();
    case 'visionprescriptionprism':
      return VisionPrescriptionPrism.empty();
    case 'visionprescription_prism':
      return VisionPrescriptionPrism.empty();
    default:
      return null;
  }
}
