// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated from profiles-resources.json by
// fhir_generator/lib/src/generate_compartment_definitions.dart

/// The published compartments: for each compartment (keyed by
/// its focal resource type), the resource types that can be in
/// it and the search parameters through which they are.
///
/// compartmentdefinition.html: a resource is in the
/// compartment of the instance one of these parameters points
/// at. The focal resource is in its own compartment; that is
/// the search's business, not this table's. A type listed in the
/// published definition with no parameter is not here.
const Map<String, Map<String, List<String>>> compartmentDefinitions = {
  'Device': {
    'Account': ['subject'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['agent'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['detail-udi', 'item-udi', 'procedure-udi', 'subdetail-udi'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['recipient', 'sender'],
    'Composition': ['author'],
    'DetectedIssue': ['author'],
    'DeviceRequest': ['device', 'performer', 'requester', 'subject'],
    'DeviceUseStatement': ['device'],
    'DiagnosticReport': ['subject'],
    'DocumentManifest': ['author', 'subject'],
    'DocumentReference': ['author', 'subject'],
    'ExplanationOfBenefit': [
      'detail-udi',
      'item-udi',
      'procedure-udi',
      'subdetail-udi',
    ],
    'Flag': ['author'],
    'Group': ['member'],
    'Invoice': ['participant'],
    'List': ['source', 'subject'],
    'Media': ['subject'],
    'MedicationAdministration': ['device'],
    'MessageHeader': ['target'],
    'Observation': ['device', 'subject'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author'],
    'RequestGroup': ['author'],
    'RiskAssessment': ['performer'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'requester'],
    'Specimen': ['subject'],
    'SupplyRequest': ['requester'],
  },
  'Encounter': {
    'CarePlan': ['encounter'],
    'CareTeam': ['encounter'],
    'ChargeItem': ['context'],
    'Claim': ['encounter'],
    'ClinicalImpression': ['encounter'],
    'Communication': ['encounter'],
    'CommunicationRequest': ['encounter'],
    'Composition': ['encounter'],
    'Condition': ['encounter'],
    'DeviceRequest': ['encounter'],
    'DiagnosticReport': ['encounter'],
    'DocumentManifest': ['related-ref'],
    'DocumentReference': ['encounter'],
    'ExplanationOfBenefit': ['encounter'],
    'Media': ['encounter'],
    'MedicationAdministration': ['context'],
    'MedicationRequest': ['encounter'],
    'NutritionOrder': ['encounter'],
    'Observation': ['encounter'],
    'Procedure': ['encounter'],
    'QuestionnaireResponse': ['encounter'],
    'RequestGroup': ['encounter'],
    'ServiceRequest': ['encounter'],
    'VisionPrescription': ['encounter'],
  },
  'Patient': {
    'Account': ['subject'],
    'AdverseEvent': ['subject'],
    'AllergyIntolerance': ['asserter', 'patient', 'recorder'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['patient'],
    'Basic': ['author', 'patient'],
    'BodyStructure': ['patient'],
    'CarePlan': ['patient', 'performer'],
    'CareTeam': ['participant', 'patient'],
    'ChargeItem': ['subject'],
    'Claim': ['patient', 'payee'],
    'ClaimResponse': ['patient'],
    'ClinicalImpression': ['subject'],
    'Communication': ['recipient', 'sender', 'subject'],
    'CommunicationRequest': ['recipient', 'requester', 'sender', 'subject'],
    'Composition': ['attester', 'author', 'subject'],
    'Condition': ['asserter', 'patient'],
    'Consent': ['patient'],
    'Coverage': ['beneficiary', 'payor', 'policy-holder', 'subscriber'],
    'CoverageEligibilityRequest': ['patient'],
    'CoverageEligibilityResponse': ['patient'],
    'DetectedIssue': ['patient'],
    'DeviceRequest': ['performer', 'subject'],
    'DeviceUseStatement': ['subject'],
    'DiagnosticReport': ['subject'],
    'DocumentManifest': ['author', 'recipient', 'subject'],
    'DocumentReference': ['author', 'subject'],
    'Encounter': ['patient'],
    'EnrollmentRequest': ['subject'],
    'EpisodeOfCare': ['patient'],
    'ExplanationOfBenefit': ['patient', 'payee'],
    'FamilyMemberHistory': ['patient'],
    'Flag': ['patient'],
    'Goal': ['patient'],
    'Group': ['member'],
    'ImagingStudy': ['patient'],
    'Immunization': ['patient'],
    'ImmunizationEvaluation': ['patient'],
    'ImmunizationRecommendation': ['patient'],
    'Invoice': ['patient', 'recipient', 'subject'],
    'List': ['source', 'subject'],
    'MeasureReport': ['patient'],
    'Media': ['subject'],
    'MedicationAdministration': ['patient', 'performer', 'subject'],
    'MedicationDispense': ['patient', 'receiver', 'subject'],
    'MedicationRequest': ['subject'],
    'MedicationStatement': ['subject'],
    'MolecularSequence': ['patient'],
    'NutritionOrder': ['patient'],
    'Observation': ['performer', 'subject'],
    'Patient': ['link'],
    'Person': ['patient'],
    'Procedure': ['patient', 'performer'],
    'Provenance': ['patient'],
    'QuestionnaireResponse': ['author', 'subject'],
    'RelatedPerson': ['patient'],
    'RequestGroup': ['participant', 'subject'],
    'ResearchSubject': ['individual'],
    'RiskAssessment': ['subject'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'subject'],
    'Specimen': ['subject'],
    'SupplyDelivery': ['patient'],
    'SupplyRequest': ['subject'],
    'VisionPrescription': ['patient'],
  },
  'Practitioner': {
    'Account': ['subject'],
    'AdverseEvent': ['recorder'],
    'AllergyIntolerance': ['asserter', 'recorder'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'AuditEvent': ['agent'],
    'Basic': ['author'],
    'CarePlan': ['performer'],
    'CareTeam': ['participant'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['care-team', 'enterer', 'payee', 'provider'],
    'ClaimResponse': ['requestor'],
    'ClinicalImpression': ['assessor'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['recipient', 'requester', 'sender'],
    'Composition': ['attester', 'author', 'subject'],
    'Condition': ['asserter'],
    'CoverageEligibilityRequest': ['enterer', 'provider'],
    'CoverageEligibilityResponse': ['requestor'],
    'DetectedIssue': ['author'],
    'DeviceRequest': ['performer', 'requester'],
    'DiagnosticReport': ['performer'],
    'DocumentManifest': ['author', 'recipient', 'subject'],
    'DocumentReference': ['authenticator', 'author', 'subject'],
    'Encounter': ['participant', 'practitioner'],
    'EpisodeOfCare': ['care-manager'],
    'ExplanationOfBenefit': ['care-team', 'enterer', 'payee', 'provider'],
    'Flag': ['author'],
    'Group': ['member'],
    'Immunization': ['performer'],
    'Invoice': ['participant'],
    'Linkage': ['author'],
    'List': ['source'],
    'Media': ['operator', 'subject'],
    'MedicationAdministration': ['performer'],
    'MedicationDispense': ['performer', 'receiver'],
    'MedicationRequest': ['requester'],
    'MedicationStatement': ['source'],
    'MessageHeader': ['author', 'enterer', 'receiver', 'responsible'],
    'NutritionOrder': ['provider'],
    'Observation': ['performer'],
    'Patient': ['general-practitioner'],
    'PaymentNotice': ['provider'],
    'PaymentReconciliation': ['requestor'],
    'Person': ['practitioner'],
    'PractitionerRole': ['practitioner'],
    'Procedure': ['performer'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author', 'source'],
    'RequestGroup': ['author', 'participant'],
    'ResearchStudy': ['principalinvestigator'],
    'RiskAssessment': ['performer'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer', 'requester'],
    'Specimen': ['collector'],
    'SupplyDelivery': ['receiver', 'supplier'],
    'SupplyRequest': ['requester'],
    'VisionPrescription': ['prescriber'],
  },
  'RelatedPerson': {
    'AdverseEvent': ['recorder'],
    'AllergyIntolerance': ['asserter'],
    'Appointment': ['actor'],
    'AppointmentResponse': ['actor'],
    'Basic': ['author'],
    'CarePlan': ['performer'],
    'CareTeam': ['participant'],
    'ChargeItem': ['enterer', 'performer-actor'],
    'Claim': ['payee'],
    'Communication': ['recipient', 'sender'],
    'CommunicationRequest': ['recipient', 'requester', 'sender'],
    'Composition': ['author'],
    'Condition': ['asserter'],
    'Coverage': ['payor', 'policy-holder', 'subscriber'],
    'DocumentManifest': ['author', 'recipient'],
    'DocumentReference': ['author'],
    'Encounter': ['participant'],
    'ExplanationOfBenefit': ['payee'],
    'Invoice': ['recipient'],
    'MedicationAdministration': ['performer'],
    'MedicationStatement': ['source'],
    'Observation': ['performer'],
    'Patient': ['link'],
    'Person': ['link'],
    'Procedure': ['performer'],
    'Provenance': ['agent'],
    'QuestionnaireResponse': ['author', 'source'],
    'RequestGroup': ['participant'],
    'Schedule': ['actor'],
    'ServiceRequest': ['performer'],
    'SupplyRequest': ['requester'],
  },
};
