name: fhir_r4_bulk
description: for supporing the R5 Version of FHIR for Dart & Flutter.
version: 0.3.0-2
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r4

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^4.0.4
  fhir_r4: ^0.3.0-1
  http: ^1.3.0
  mime: ^2.0.0
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.25.15
