import 'dart:io';

import 'package:fhir_r4/fhir_r4.dart';
import 'package:fhir_r4_cql/fhir_r4_cql.dart';
import 'package:test/test.dart';

import '../test_helpers/cql_test_helpers.dart';

/// Test runner for the CQF Reference Implementation's CqlTestSuite.cql.
///
/// This is a comprehensive, self-validating test suite from:
/// https://github.com/cqframework/clinical_quality_language
///
/// Each `define test_*` in the CQL returns `"<name> TEST PASSED"` on success,
/// or triggers a runtime Message() error on failure via the TestMessage() helper.
///
/// We parse and execute the entire library once, then check each test define's
/// result individually.
void main() {
  final engineDir = Directory('cql/cqf-engine');
  if (!engineDir.existsSync()) {
    print('CQF engine tests not downloaded. '
        'Run: bash utils/download_engine_tests.sh');
    return;
  }

  final suiteFile = File('cql/cqf-engine/CqlTestSuite.cql');
  if (!suiteFile.existsSync()) {
    print('CqlTestSuite.cql not found');
    return;
  }

  final source = suiteFile.readAsStringSync();

  // Extract all `define test_*:` names
  final testNames = RegExp(r'define (test_\w+):')
      .allMatches(source)
      .map((m) => m.group(1)!)
      .toList();

  group('CqlTestSuite', () {
    late Map<String, dynamic> results;

    setUpAll(() async {
      final library = parseAndBuildLibrary(source);
      final context = <String, dynamic>{
        'startTimestamp': FhirDateTime.fromString('2018-01-01T07:00:00.0-07:00'),
      };
      results = (await library.execute(context)) as Map<String, dynamic>;
    });

    for (final name in testNames) {
      final skipReason = _knownFailures[name];
      test(name, () {
        // The expected pattern: the test name without "test_" prefix + " TEST PASSED"
        final baseName = name.replaceFirst('test_', '');
        final expected = '$baseName TEST PASSED';
        final actual = results[name];
        expect(actual, equals(expected),
            reason: 'Expected: $expected\nActual: $actual');
      }, skip: skipReason);
    }
  });
}

/// Known failures with skip reasons, categorized by root cause.
/// Total: 593 failures out of 1948 tests (1355 passing = 69.6%).
///
/// Major categories:
/// - Interval Expand: 167 tests (not yet implemented)
/// - Interval Collapse: 47 tests (not yet implemented)
/// - Meets/MeetsBefore/MeetsAfter: 58 tests (edge cases)
/// - Logical operators: 30 tests (toString overload resolution)
/// - String operations: 30 tests (null handling)
/// - Interval Union/Intersect/Except: 49 tests (edge cases)
/// - Equality edge cases: 18 tests
/// - Quantity arithmetic: 26 tests
/// - Type conversion: 19 tests
/// - Other: 70+ tests
// ignore_for_file: lines_longer_than_80_chars
const _knownFailures = <String, String>{
  // After/Before edge cases (10 tests)
  'test_After_HourBeforeNormalizeZones': 'After/Before edge cases',
  'test_After_ImpreciseNotAfterDateIvl': 'After/Before edge cases',
  'test_After_NotAfterImpreciseDateIvl': 'After/Before edge cases',
  'test_After_SameHourNormalizeZones': 'After/Before edge cases',
  'test_After_UnknownBegNotAfterDateIvl': 'After/Before edge cases',
  'test_After_UnknownBegNotAfterIntIvl': 'After/Before edge cases',
  'test_Before_ImpreciseNotBeforeDateIvl': 'After/Before edge cases',
  'test_Before_NotBeforeImpreciseDateIvl': 'After/Before edge cases',
  'test_Before_UnknownEndNotBeforeDateIvl': 'After/Before edge cases',
  'test_Before_UnknownEndNotBeforeIntIvl': 'After/Before edge cases',
  // Aggregate/math edge cases (4 tests)
  'test_GeometricMean_Null': 'Aggregate/math edge cases',
  'test_Ln_Four': 'Aggregate/math edge cases',
  'test_Mode_bi_modal': 'Aggregate/math edge cases',
  'test_Product_Null': 'Aggregate/math edge cases',
  // Code/Concept edge cases (4 tests)
  'test_CodeWithoutDisplayAndVersionNull': 'Code/Concept edge cases',
  'test_ConceptWithoutDisplayAndVersionEqual': 'Code/Concept edge cases',
  'test_ConceptWithoutDisplayAndVersionNotEqual': 'Code/Concept edge cases',
  'test_ConceptWithoutDisplayAndVersionNull': 'Code/Concept edge cases',
  // DifferenceBetween edge cases (6 tests)
  'test_DiffComp_EqualTo40DaysAfter': 'DifferenceBetween edge cases',
  'test_DiffComp_FortyDaysEqualToDaysBetween': 'DifferenceBetween edge cases',
  'test_DifferenceBetween_Date_EqualTo40DaysAfter': 'DifferenceBetween edge cases',
  'test_DifferenceBetween_Date_FortyDaysEqualToDaysBetween': 'DifferenceBetween edge cases',
  'test_DifferenceBetween_Date_WeeksBetweenUncertainty': 'DifferenceBetween edge cases',
  'test_DifferenceBetween_WeeksBetweenUncertainty': 'DifferenceBetween edge cases',
  // Equality edge cases (18 tests)
  'test_Equal_DateAndDateTimeEqual': 'Equality edge cases',
  'test_Equal_DateAndDateTimeUncertainEqual': 'Equality edge cases',
  'test_Equal_DateTimeAndDateEqual': 'Equality edge cases',
  'test_Equal_DateTimeAndDateUncertainEqual': 'Equality edge cases',
  'test_Equal_DifferingPrecision': 'Equality edge cases',
  'test_Equal_EqualQuantityOpenClosed': 'Equality edge cases',
  'test_Equal_FirstListHasNull': 'Equality edge cases',
  'test_Equal_SecondListHasNull': 'Equality edge cases',
  'test_Equal_TupleDifferentKeys': 'Equality edge cases',
  'test_Equal_UncertTuplesWithDiffNullFields': 'Equality edge cases',
  'test_NotEqual_DateAndDateTimeEqual': 'Equality edge cases',
  'test_NotEqual_DateAndDateTimeUncertainEqual': 'Equality edge cases',
  'test_NotEqual_DateTimeAndDateEqual': 'Equality edge cases',
  'test_NotEqual_DateTimeAndDateUncertainEqual': 'Equality edge cases',
  'test_NotEqual_DifferingPrecision': 'Equality edge cases',
  'test_NotEqual_EqualQuantityOpenClosed': 'Equality edge cases',
  'test_NotEqual_TupleDifferentKeys': 'Equality edge cases',
  'test_NotEqual_UncertTuplesWithDiffNullFields': 'Equality edge cases',
  // Equivalence edge cases (1 tests)
  'test_Equivalent_DifferentTypesLists': 'Equivalence edge cases',
  // Imprecise/unknown interval containment (12 tests)
  'test_Contains_ImpreciseMayContainDate': 'Imprecise/unknown interval containment',
  'test_Contains_MayContainImpreciseDate': 'Imprecise/unknown interval containment',
  'test_Contains_UnknownBegContainsDate': 'Imprecise/unknown interval containment',
  'test_Contains_UnknownBegMayContainDate': 'Imprecise/unknown interval containment',
  'test_Contains_UnknownEndContainsDate': 'Imprecise/unknown interval containment',
  'test_Contains_UnknownEndMayContainDate': 'Imprecise/unknown interval containment',
  'test_In_ImpreciseMayContainDate': 'Imprecise/unknown interval containment',
  'test_In_MayContainImpreciseDate': 'Imprecise/unknown interval containment',
  'test_In_UnknownBegContainsDate': 'Imprecise/unknown interval containment',
  'test_In_UnknownBegMayContainDate': 'Imprecise/unknown interval containment',
  'test_In_UnknownEndContainsDate': 'Imprecise/unknown interval containment',
  'test_In_UnknownEndMayContainDate': 'Imprecise/unknown interval containment',
  // Intersect edge cases (8 tests)
  'test_Intersect_IntersectOnAll': 'Intersect edge cases',
  'test_Intersect_IntersectOnEvens': 'Intersect edge cases',
  'test_Intersect_IntersectOnFive': 'Intersect edge cases',
  'test_Intersect_IntersectTuples': 'Intersect edge cases',
  'test_Intersect_IntersectionOnFourDuplicates': 'Intersect edge cases',
  'test_Intersect_MultipleNullInListIntersect': 'Intersect edge cases',
  'test_Intersect_NestedIntersects': 'Intersect edge cases',
  'test_Intersect_NoIntersection': 'Intersect edge cases',
  // Interval Collapse not yet implemented (47 tests)
  'test_DtIvlCollapse_DateTimeCollapseAdjacent': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseDisjoint': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseDisjointReversed': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseEmpty': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseImpreciseBoundary': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseNoPer': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseOverlap': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseOverlapContained': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseOverlapContainedEdge': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseOverlapContainedEdge2': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseOverlapMultipleCombine': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapsePerDay': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapsePerMs': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseSeparatedPerDay': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseSeparatedPerHour': 'Interval Collapse not yet implemented',
  'test_DtIvlCollapse_DateTimeCollapseSingleInterval': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseAdjacent': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseDisjoint': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseDisjointReversed': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseEmpty': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseOverlap': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseOverlapContained': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseOverlapContainedEdge': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseOverlapContainedEdge2': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseOverlapMultipleCombine': 'Interval Collapse not yet implemented',
  'test_IntIvlCollapse_IntCollapseSingleInterval': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseNullHighIntervalList': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseNullLowIntervalList': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseQuantityIntervalListWithNullHighNoOverlap': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseQuantityIntervalListWithNullLowNoOverlap': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseQuantityIntervalListWithNulls': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseQuantityNullHighUnitsWithinPer': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_CollapseQuantityNullLowUnitsWithinPer': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_DateTimeNullEndCollapse': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_DateTimeNullEndCollapseNoOverlap': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_DateTimeNullStartCollapse': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_DateTimeNullStartCollapseNoOverlap': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_DateTimeNullStartEndCollapse': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_NullInCollapse': 'Interval Collapse not yet implemented',
  'test_NullIvlCollapse_NullPerCollapse': 'Interval Collapse not yet implemented',
  'test_NumIvlCollapse_IntCollapseNoPer': 'Interval Collapse not yet implemented',
  'test_NumIvlCollapse_IntCollapsePerUnit1': 'Interval Collapse not yet implemented',
  'test_NumIvlCollapse_IntCollapseSeparatedListPer3': 'Interval Collapse not yet implemented',
  'test_QtyIvlCollapse_CollapseSeparatedQuantity': 'Interval Collapse not yet implemented',
  'test_QtyIvlCollapse_CollapseSeparatedQuantityPer3': 'Interval Collapse not yet implemented',
  'test_QtyIvlCollapse_QuantityIntervalCollapseNoPer': 'Interval Collapse not yet implemented',
  'test_QtyIvlCollapse_QuantityIntervalCollapsePerUnit1': 'Interval Collapse not yet implemented',
  // Interval Except edge cases (16 tests)
  'test_DtIvlExcept_DateTimeBeforeExcept': 'Interval Except edge cases',
  'test_DtIvlExcept_DateTimeMeetsExcept': 'Interval Except edge cases',
  'test_DtIvlExcept_DateTimeOverlapsExcept': 'Interval Except edge cases',
  'test_Except_ExceptEverything': 'Interval Except edge cases',
  'test_Except_ExceptFiveThree': 'Interval Except edge cases',
  'test_Except_ExceptNoOp': 'Interval Except edge cases',
  'test_Except_ExceptNull': 'Interval Except edge cases',
  'test_Except_ExceptThreeFour': 'Interval Except edge cases',
  'test_Except_ExceptTuples': 'Interval Except edge cases',
  'test_Except_MultipleNullExcept': 'Interval Except edge cases',
  'test_Except_NothingExceptSomething': 'Interval Except edge cases',
  'test_Except_SomethingExceptNothing': 'Interval Except edge cases',
  'test_Except_ThreeFourExcept': 'Interval Except edge cases',
  'test_IntIvlExcept_IntBeforeExcept': 'Interval Except edge cases',
  'test_IntIvlExcept_IntMeetsExcept': 'Interval Except edge cases',
  'test_IntIvlExcept_IntOverlapsExcept': 'Interval Except edge cases',
  // Interval Expand not yet implemented (167 tests)
  'test_DateIvlExpand_BadPerGram': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_BadPerMinute': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerDay': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerMonth': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerMonthTrunc': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerWeek': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerYear': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_ClosedSinglePerYearTrunc': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MidBoundariesPerDay': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MidBoundariesPerMonth': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MidBoundariesPerYear': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MismatchPrecision': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MismatchPrecisionEmpty': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_MonthDayPer': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NoPerDefaultDay': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NoPerDefaultMonth': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NoPerDefaultMonthWithMismatch': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NoPerDefaultYear': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NonOverlapping': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NullBoth': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NullClose': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NullInList': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_NullOpen': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_OpenBoth': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_OpenEnd': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_OpenStart': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_Overlapping': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_YearDayPer': 'Interval Expand not yet implemented',
  'test_DateIvlExpand_YearMonthPer': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_BadPerGram': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_DayPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_HourPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MinPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MismatchPrecision': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MismatchPrecisionEmpty': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MonthPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_MsPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultMS': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultMin': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultSec': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NoPerDefaultYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NonOverlapping': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NullBoth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NullClose': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NullInList': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_NullOpen': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_OpenBoth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_OpenEnd': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_OpenStart': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_Overlapping': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_SecPrecPerYear': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerDay': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerHour': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerMinute': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerMonth': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerSecond': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerWeek': 'Interval Expand not yet implemented',
  'test_DateTimeIvlExpand_YearPrecPerYear': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_BadPerMinute': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_ClosedSingle': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_ClosedSingle1': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_ClosedSingle2': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_NoPer': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_NonOverlapping': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_NullClose': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_NullInList': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_NullOpen': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_OpenBoth': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_OpenEnd': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_OpenStart': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_Overlapping': 'Interval Expand not yet implemented',
  'test_DecIvlExpand_PerTooBig': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_BadPerMinute': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_ClosedSinglePer1': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_ClosedSinglePer3': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_ClosedSinglePer3NoteTheWidth': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_NoPer': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_NonOverlapping': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_NullClose': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_NullInList': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_NullOpen': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_OpenBoth': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_OpenEnd': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_OpenStart': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_Overlapping': 'Interval Expand not yet implemented',
  'test_IntIvlExpand_PerTooBig': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleGPerG': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleGPerGDecimal': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleGPerMG': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleMGPerGTrunc': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleMGPerMGDecimal': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_ClosedSingleMGPerMGTrunc': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NoPerDefaultG': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NonOverlapping': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NullBoth': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NullClose': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NullInList': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_NullOpen': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_OpenBoth': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_OpenBothDecimal': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_OpenBothDecimalTrunc': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_OpenEnd': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_OpenStart': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_Overlapping': 'Interval Expand not yet implemented',
  'test_QtyIvlExpand_PerTooBig': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_HourPrecPerHour': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_HourPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_HourPrecPerMinute': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_HourPrecPerSecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MinPrecPerHour': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MinPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MinPrecPerMinute': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MinPrecPerSecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MsPrecPerHour': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MsPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MsPrecPerMinute': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_MsPrecPerSecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_SecPrecPerHour': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_SecPrecPerMillisecond': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_SecPrecPerMinute': 'Interval Expand not yet implemented',
  'test_TimeIvlExpand_SecPrecPerSecond': 'Interval Expand not yet implemented',
  // Interval Intersect edge cases (13 tests)
  'test_DtIvlIntersect_DateTimeBeginsIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeDifferentPrecisionIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeDuringIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeEndsIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeMeetsIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeOverlapsIntersect': 'Interval Intersect edge cases',
  'test_DtIvlIntersect_DateTimeSameAsIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntBeginsIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntDuringIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntEndsIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntMeetsIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntOverlapsIntersect': 'Interval Intersect edge cases',
  'test_IntIvlIntersect_IntSameAsIntersect': 'Interval Intersect edge cases',
  // Interval Union edge cases (20 tests)
  'test_DtIvlUnion_DateTimeBeginsUnion': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeClosedUnionClosed': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeClosedUnionOpen': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeDuringUnion': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeEndsUnion': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeMeetsUnion': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeOpenUnionClosed': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeOpenUnionOpen': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeOverlapsUnion': 'Interval Union edge cases',
  'test_DtIvlUnion_DateTimeSameAsUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntBeginsUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntClosedUnionClosed': 'Interval Union edge cases',
  'test_IntIvlUnion_IntClosedUnionOpen': 'Interval Union edge cases',
  'test_IntIvlUnion_IntDuringUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntEndsUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntMeetsUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntOpenUnionClosed': 'Interval Union edge cases',
  'test_IntIvlUnion_IntOpenUnionOpen': 'Interval Union edge cases',
  'test_IntIvlUnion_IntOverlapsUnion': 'Interval Union edge cases',
  'test_IntIvlUnion_IntSameAsUnion': 'Interval Union edge cases',
  // Logical operator edge cases (30 tests)
  'test_And_FF': 'Logical operator edge cases',
  'test_And_FN': 'Logical operator edge cases',
  'test_And_FT': 'Logical operator edge cases',
  'test_And_NF': 'Logical operator edge cases',
  'test_And_NN': 'Logical operator edge cases',
  'test_And_NT': 'Logical operator edge cases',
  'test_And_TF': 'Logical operator edge cases',
  'test_And_TN': 'Logical operator edge cases',
  'test_And_TT': 'Logical operator edge cases',
  'test_Not_NotFalse': 'Logical operator edge cases',
  'test_Not_NotNull': 'Logical operator edge cases',
  'test_Not_NotTrue': 'Logical operator edge cases',
  'test_Or_FF': 'Logical operator edge cases',
  'test_Or_FN': 'Logical operator edge cases',
  'test_Or_FT': 'Logical operator edge cases',
  'test_Or_NF': 'Logical operator edge cases',
  'test_Or_NN': 'Logical operator edge cases',
  'test_Or_NT': 'Logical operator edge cases',
  'test_Or_TF': 'Logical operator edge cases',
  'test_Or_TN': 'Logical operator edge cases',
  'test_Or_TT': 'Logical operator edge cases',
  'test_XOr_FF': 'Logical operator edge cases',
  'test_XOr_FN': 'Logical operator edge cases',
  'test_XOr_FT': 'Logical operator edge cases',
  'test_XOr_NF': 'Logical operator edge cases',
  'test_XOr_NN': 'Logical operator edge cases',
  'test_XOr_NT': 'Logical operator edge cases',
  'test_XOr_TF': 'Logical operator edge cases',
  'test_XOr_TN': 'Logical operator edge cases',
  'test_XOr_TT': 'Logical operator edge cases',
  // Meets edge cases (13 tests)
  'test_Meets_DateIvlNotMeetsNegInfBeg': 'Meets edge cases',
  'test_Meets_DateIvlNotMeetsPosInfEnd': 'Meets edge cases',
  'test_Meets_ImpreciseMayMeetAfterDateIvl': 'Meets edge cases',
  'test_Meets_ImpreciseMayMeetBeforeDateIvl': 'Meets edge cases',
  'test_Meets_MayMeetAfterDayOfImpreciseIvl': 'Meets edge cases',
  'test_Meets_MayMeetAfterImpreciseDateIvl': 'Meets edge cases',
  'test_Meets_MayMeetBeforeDayOfImpreciseIvl': 'Meets edge cases',
  'test_Meets_MayMeetBeforeImpreciseDateIvl': 'Meets edge cases',
  'test_Meets_NotMeetsDayOfIvl': 'Meets edge cases',
  'test_Meets_UnknownBegNotMeetsDateIvl': 'Meets edge cases',
  'test_Meets_UnknownBegNotMeetsIntIvl': 'Meets edge cases',
  'test_Meets_UnknownEndNotMeetsDateIvl': 'Meets edge cases',
  'test_Meets_UnknownEndNotMeetsIntIvl': 'Meets edge cases',
  // MeetsAfter edge cases (31 tests)
  'test_MeetsAfter_DateIvlMayMeetBeforeUnknownBeg': 'MeetsAfter edge cases',
  'test_MeetsAfter_DateIvlNotMeetsNegInfBeg': 'MeetsAfter edge cases',
  'test_MeetsAfter_DateIvlNotMeetsPosInfEnd': 'MeetsAfter edge cases',
  'test_MeetsAfter_ImpreciseMayMeetAfterDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_IntIvlMayMeetBeforeUnknownBeg': 'MeetsAfter edge cases',
  'test_MeetsAfter_MayMeetAfterDayOfImpreciseIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MayMeetAfterImpreciseDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MeetsAfterDayOfIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MeetsBeforeDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MeetsBeforeDayOfIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MeetsBeforeIntIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_MeetsBeforeRealIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_NegInfBegMeetsBeforeDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_NegInfBegMeetsBeforeIntIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_NotMeetsDayOfIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownBegMeetsBeforeDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownBegMeetsBeforeIntIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownBegNotMeetsDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownBegNotMeetsIntIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownEndMayMeetBeforeDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownEndMayMeetBeforeIntIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownEndNotMeetsDateIvl': 'MeetsAfter edge cases',
  'test_MeetsAfter_UnknownEndNotMeetsIntIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_MeetsAfterDateIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_MeetsAfterIntIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_MeetsAfterRealIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_PosInfEndMeetsAfterDateIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_PosInfEndMeetsAfterIntIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_UnknownEndMeetsAfterDateIvl': 'MeetsAfter edge cases',
  'test_MeetsBefore_UnknownEndMeetsAfterIntIvl': 'MeetsAfter edge cases',
  'test_Meets_MeetsAfterDayOfIvl': 'MeetsAfter edge cases',
  // MeetsBefore edge cases (14 tests)
  'test_MeetsBefore_DateIvlMayMeetAfterUnknownEnd': 'MeetsBefore edge cases',
  'test_MeetsBefore_DateIvlNotMeetsNegInfBeg': 'MeetsBefore edge cases',
  'test_MeetsBefore_DateIvlNotMeetsPosInfEnd': 'MeetsBefore edge cases',
  'test_MeetsBefore_ImpreciseMayMeetBeforeDateIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_IntIvlMayMeetAfterUnknownEnd': 'MeetsBefore edge cases',
  'test_MeetsBefore_MayMeetBeforeDayOfImpreciseIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_MayMeetBeforeImpreciseDateIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_NotMeetsDayOfIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownBegMayMeetAfterDateIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownBegMayMeetAfterIntIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownBegNotMeetsDateIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownBegNotMeetsIntIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownEndNotMeetsDateIvl': 'MeetsBefore edge cases',
  'test_MeetsBefore_UnknownEndNotMeetsIntIvl': 'MeetsBefore edge cases',
  // Other (70 tests)
  'test_Combine_CombineNull': 'Other',
  'test_Combine_CombineNullItem': 'Other',
  'test_Combine_NoSeparator': 'Other',
  'test_Combine_Separator': 'Other',
  'test_Concat_ConcatNull': 'Other',
  'test_Concat_HelloWorld': 'Other',
  'test_Concat_HelloWorldVariables': 'Other',
  'test_Concat_Sentence': 'Other',
  'test_Distinct_DuplicateNulls': 'Other',
  'test_Distinct_DupsTuples': 'Other',
  'test_Distinct_LotsOfDups': 'Other',
  'test_Distinct_NoDups': 'Other',
  'test_Distinct_NoDupsTuples': 'Other',
  'test_First_Tuples': 'Other',
  'test_Flatten_ListOfLists': 'Other',
  'test_In_TupleIsIn': 'Other',
  'test_IncludedIn_NullIncluded': 'Other',
  'test_IncludedIn_NullIncludes': 'Other',
  'test_IncludedIn_TuplesIncluded': 'Other',
  'test_Includes_NullIncluded': 'Other',
  'test_Includes_NullIncludes': 'Other',
  'test_Includes_TuplesIncluded': 'Other',
  'test_IndexOf_IndexOfThirdTuple': 'Other',
  'test_Indexer_HelloWorldSix': 'Other',
  'test_Indexer_HelloWorldTwenty': 'Other',
  'test_Indexer_HelloWorldZero': 'Other',
  'test_Indexer_NullIndex': 'Other',
  'test_Indexer_NullString': 'Other',
  'test_IsFalse_FalseIsFalse': 'Other',
  'test_IsFalse_NullIsFalse': 'Other',
  'test_IsFalse_TrueIsFalse': 'Other',
  'test_IsNull_NonNullVarIsNull': 'Other',
  'test_IsNull_NullIsNull': 'Other',
  'test_IsNull_NullVarIsNull': 'Other',
  'test_IsNull_StringIsNull': 'Other',
  'test_IsTrue_FalseIsTrue': 'Other',
  'test_IsTrue_NullIsTrue': 'Other',
  'test_IsTrue_TrueIsTrue': 'Other',
  'test_Last_Tuples': 'Other',
  'test_Length_ElevenLetters': 'Other',
  'test_Length_NullString': 'Other',
  'test_Lower_CamelC': 'Other',
  'test_Lower_LowerC': 'Other',
  'test_Lower_NullString': 'Other',
  'test_Lower_UpperC': 'Other',
  'test_OverlapsAfterDT_MayOverlapAfterDayOfImpreciseIvl': 'Other',
  'test_OverlapsAfterDT_UnknownOverlap': 'Other',
  'test_OverlapsBeforeDT_MayOverlapBeforeDayOfImpreciseIvl': 'Other',
  'test_OverlapsBeforeDT_UnknownOverlap': 'Other',
  'test_OverlapsDT_ImpreciseOverlap': 'Other',
  'test_PositionOf_found': 'Other',
  'test_PositionOf_notFound': 'Other',
  'test_PositionOf_nullPattern': 'Other',
  'test_PositionOf_nullString': 'Other',
  'test_ProperIncludedIn_NullIncluded': 'Other',
  'test_ProperIncludedIn_NullIncludes': 'Other',
  'test_ProperIncludedIn_TuplesIncluded': 'Other',
  'test_ProperIncludes_NullIncluded': 'Other',
  'test_ProperIncludes_NullIncludes': 'Other',
  'test_ProperIncludes_TuplesIncluded': 'Other',
  'test_ProperlyIncludedIn_NotProperlyIncludesDayOfIvlSameEdges': 'Other',
  'test_ProperlyIncludes_NotProperlyIncludesDayOfIvlSameEdges': 'Other',
  'test_Split_CommaSeparated': 'Other',
  'test_Split_SeparateNull': 'Other',
  'test_Split_SeparateUsingNull': 'Other',
  'test_Split_SeparatorNotUsed': 'Other',
  'test_Upper_CamelC': 'Other',
  'test_Upper_LowerC': 'Other',
  'test_Upper_NullString': 'Other',
  'test_Upper_UpperC': 'Other',
  // Predecessor/Successor edge cases (1 tests)
  'test_Predecessor_Rs': 'Predecessor/Successor edge cases',
  // Quantity arithmetic edge cases (26 tests)
  'test_Avg_has_null_q': 'Quantity arithmetic edge cases',
  'test_Avg_not_null_q': 'Quantity arithmetic edge cases',
  'test_Avg_q_diff_units': 'Quantity arithmetic edge cases',
  'test_Median_dup_vals_even_q': 'Quantity arithmetic edge cases',
  'test_Median_dup_vals_odd_q': 'Quantity arithmetic edge cases',
  'test_Median_even_q': 'Quantity arithmetic edge cases',
  'test_Median_has_null_q': 'Quantity arithmetic edge cases',
  'test_Median_odd_q': 'Quantity arithmetic edge cases',
  'test_Median_q_diff_units': 'Quantity arithmetic edge cases',
  'test_PopulationStd_q': 'Quantity arithmetic edge cases',
  'test_PopulationStd_q_diff_units': 'Quantity arithmetic edge cases',
  'test_PopulationVariance_q_diff_units': 'Quantity arithmetic edge cases',
  'test_PopulationVariance_v_q': 'Quantity arithmetic edge cases',
  'test_Product_Quantity': 'Quantity arithmetic edge cases',
  'test_Product_Quantity_Zero': 'Quantity arithmetic edge cases',
  'test_Quantity_AddUcum': 'Quantity arithmetic edge cases',
  'test_Quantity_SubtractUcum': 'Quantity arithmetic edge cases',
  'test_Quantity_mul_d_q': 'Quantity arithmetic edge cases',
  'test_Quantity_mul_q_q_diff': 'Quantity arithmetic edge cases',
  'test_Std_q': 'Quantity arithmetic edge cases',
  'test_Std_q_diff_units': 'Quantity arithmetic edge cases',
  'test_Sum_q_diff_units': 'Quantity arithmetic edge cases',
  'test_Sum_unmatched_units_q': 'Quantity arithmetic edge cases',
  'test_Variance_q2': 'Quantity arithmetic edge cases',
  'test_Variance_q_diff_units': 'Quantity arithmetic edge cases',
  'test_Variance_v_q': 'Quantity arithmetic edge cases',
  // SameAs interval edge cases (12 tests)
  'test_SameAsIvl_DateTimeAndDateComparisonEqual': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeDayPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeHourPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeMinutePrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeMonthPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeSecondPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateTimeYearPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_DateYearPrecisionSame': 'SameAs interval edge cases',
  'test_SameAsIvl_TimeIntervalComparisonNotSame': 'SameAs interval edge cases',
  'test_SameAsIvl_TimeIntervalComparisonSame': 'SameAs interval edge cases',
  'test_SameAsIvl_TimeOpenAndClosed': 'SameAs interval edge cases',
  'test_SameAsIvl_TimeOpenEnded': 'SameAs interval edge cases',
  // String/null handling edge cases (30 tests)
  'test_Coalesce_AllNull': 'String/null handling edge cases',
  'test_Coalesce_FooNullNullBar': 'String/null handling edge cases',
  'test_Coalesce_ListArgAllNull': 'String/null handling edge cases',
  'test_Coalesce_ListArgStartsWithNull': 'String/null handling edge cases',
  'test_Coalesce_ListExpressionRef': 'String/null handling edge cases',
  'test_Coalesce_NullNullHelloNullWorld': 'String/null handling edge cases',
  'test_Coalesce_UnionAsList': 'String/null handling edge cases',
  'test_EndsWith_BlankEndsWithFoo': 'String/null handling edge cases',
  'test_EndsWith_EndsWithNull': 'String/null handling edge cases',
  'test_EndsWith_EndsWithNullAsString': 'String/null handling edge cases',
  'test_EndsWith_FooBarEndsWithBar': 'String/null handling edge cases',
  'test_EndsWith_FooBarEndsWithFoo': 'String/null handling edge cases',
  'test_EndsWith_NullAsStringEndsWith': 'String/null handling edge cases',
  'test_EndsWith_NullEndsWith': 'String/null handling edge cases',
  'test_StartsWith_FooBarStartsWithBar': 'String/null handling edge cases',
  'test_StartsWith_FooBarStartsWithBlank': 'String/null handling edge cases',
  'test_StartsWith_FooBarStartsWithFoo': 'String/null handling edge cases',
  'test_StartsWith_NullAsStringStartsWith': 'String/null handling edge cases',
  'test_StartsWith_NullStartsWith': 'String/null handling edge cases',
  'test_StartsWith_StartsWithNull': 'String/null handling edge cases',
  'test_StartsWith_StartsWithNullAsString': 'String/null handling edge cases',
  'test_Substring_NegativeLength': 'String/null handling edge cases',
  'test_Substring_NullStart': 'String/null handling edge cases',
  'test_Substring_NullString': 'String/null handling edge cases',
  'test_Substring_Or': 'String/null handling edge cases',
  'test_Substring_StartTooLow': 'String/null handling edge cases',
  'test_Substring_StartZero': 'String/null handling edge cases',
  'test_Substring_TooMuchLength': 'String/null handling edge cases',
  'test_Substring_World': 'String/null handling edge cases',
  'test_Substring_ZeroLength': 'String/null handling edge cases',
  // Time/Now edge cases (1 tests)
  'test_Now_Var': 'Time/Now edge cases',
  // Type conversion edge cases (19 tests)
  'test_FromCode_codeCode': 'Type conversion edge cases',
  'test_FromCode_codeConcept': 'Type conversion edge cases',
  'test_FromString_integerDropDecimal': 'Type conversion edge cases',
  'test_TimeFrom_NoTime': 'Type conversion edge cases',
  'test_ToConcept_IsValid': 'Type conversion edge cases',
  'test_ToDecimal_TooLargeDec': 'Type conversion edge cases',
  'test_ToDecimal_TooPrecise': 'Type conversion edge cases',
  'test_ToDecimal_TooSmallDec': 'Type conversion edge cases',
  'test_ToDecimal_WrongFormat': 'Type conversion edge cases',
  'test_ToInteger_TooLargeInt': 'Type conversion edge cases',
  'test_ToInteger_TooSmallInt': 'Type conversion edge cases',
  'test_ToList_FiveInFive': 'Type conversion edge cases',
  'test_ToList_FourInFive': 'Type conversion edge cases',
  'test_ToList_LengthOfNull': 'Type conversion edge cases',
  'test_ToQuantity_TooLargeQuantity': 'Type conversion edge cases',
  'test_ToQuantity_TooSmallQuantity': 'Type conversion edge cases',
  'test_ToQuantity_WrongFormatQuantity': 'Type conversion edge cases',
  'test_ToTime_SecondTooHigh': 'Type conversion edge cases',
  'test_Width_IntWidthMinToThree': 'Type conversion edge cases',
  // Union edge cases (7 tests)
  'test_Union_Disjoint': 'Union edge cases',
  'test_Union_NestedToFifteen': 'Union edge cases',
  'test_Union_NullUnion': 'Union edge cases',
  'test_Union_OneToFiveOverlapped': 'Union edge cases',
  'test_Union_OneToFiveOverlappedWithNulls': 'Union edge cases',
  'test_Union_OneToTen': 'Union edge cases',
  'test_Union_UnionNull': 'Union edge cases',
  // Unknown bound interval inclusion (13 tests)
  'test_IncludedIn_UnknownBegIncludedInDateIvl': 'Unknown bound interval inclusion',
  'test_IncludedIn_UnknownBegIncludedInIntIvl': 'Unknown bound interval inclusion',
  'test_IncludedIn_UnknownBegMayBeIncludedInIntIvl': 'Unknown bound interval inclusion',
  'test_IncludedIn_UnknownEndIncludedInDateIvl': 'Unknown bound interval inclusion',
  'test_IncludedIn_UnknownEndIncludedInIntIvl': 'Unknown bound interval inclusion',
  'test_IncludedIn_UnknownEndMayBeIncludedInIntIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownBegIncludesDateIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownBegIncludesIntIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownBegMayIncludeIntIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownEndIncludesDateIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownEndIncludesIntIvl': 'Unknown bound interval inclusion',
  'test_Includes_UnknownEndMayIncludeIntIvl': 'Unknown bound interval inclusion',
  'test_ProperlyIncludes_UnknownEndMayProperlyIncludeIntIvl': 'Unknown bound interval inclusion',
};
