import 'package:realm/realm.dart';
@RealmModel()
class _ObservationRealm {
  late _R4ResourceTypeRealm resourceType;
  @PrimaryKey() late String id;
  late _FhirMetaRealm meta;
  late _FhirUriRealm implicitRules;
  late _PrimitiveElementRealm implicitRulesElement;
  late _FhirCodeRealm language;
  late _PrimitiveElementRealm languageElement;
  late _NarrativeRealm text;
  late List<_ResourceRealm> contained;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late List<_IdentifierRealm> identifier;
  late List<_ReferenceRealm> basedOn;
  late List<_ReferenceRealm> partOf;
  late _FhirCodeRealm status;
  late _PrimitiveElementRealm statusElement;
  late List<_CodeableConceptRealm> category;
  late _CodeableConceptRealm code;
  late _ReferenceRealm subject;
  late List<_ReferenceRealm> focus;
  late _ReferenceRealm encounter;
  late String effectiveDateTime;
  late _PrimitiveElementRealm effectiveDateTimeElement;
  late _PeriodRealm effectivePeriod;
  late _TimingRealm effectiveTiming;
  late _FhirInstantRealm effectiveInstant;
  late _PrimitiveElementRealm effectiveInstantElement;
  late _FhirInstantRealm issued;
  late _PrimitiveElementRealm issuedElement;
  late List<_ReferenceRealm> performer;
  late _QuantityRealm valueQuantity;
  late _CodeableConceptRealm valueCodeableConcept;
  late String valueString;
  late _PrimitiveElementRealm valueStringElement;
  late _FhirBooleanRealm valueBoolean;
  late _PrimitiveElementRealm valueBooleanElement;
  late _FhirIntegerRealm valueInteger;
  late _PrimitiveElementRealm valueIntegerElement;
  late _RangeRealm valueRange;
  late _RatioRealm valueRatio;
  late _SampledDataRealm valueSampledData;
  late _FhirTimeRealm valueTime;
  late _PrimitiveElementRealm valueTimeElement;
  late String valueDateTime;
  late _PrimitiveElementRealm valueDateTimeElement;
  late _PeriodRealm valuePeriod;
  late _CodeableConceptRealm dataAbsentReason;
  late List<_CodeableConceptRealm> interpretation;
  late List<_AnnotationRealm> note;
  late _CodeableConceptRealm bodySite;
  late _CodeableConceptRealm method;
  late _ReferenceRealm specimen;
  late _ReferenceRealm device;
  late List<_ObservationReferenceRangeRealm> referenceRange;
  late List<_ReferenceRealm> hasMember;
  late List<_ReferenceRealm> derivedFrom;
  late List<_ObservationComponentRealm> component;
}
@RealmModel()
class _ObservationReferenceRangeRealm {
  @PrimaryKey() late String id;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late _QuantityRealm low;
  late _QuantityRealm high;
  late _CodeableConceptRealm type;
  late List<_CodeableConceptRealm> appliesTo;
  late _RangeRealm age;
  late String text;
  late _PrimitiveElementRealm textElement;
}
@RealmModel()
class _ObservationComponentRealm {
  @PrimaryKey() late String id;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late _CodeableConceptRealm code;
  late _QuantityRealm valueQuantity;
  late _CodeableConceptRealm valueCodeableConcept;
  late String valueString;
  late _PrimitiveElementRealm valueStringElement;
  late _FhirBooleanRealm valueBoolean;
  late _PrimitiveElementRealm valueBooleanElement;
  late _FhirIntegerRealm valueInteger;
  late _PrimitiveElementRealm valueIntegerElement;
  late _RangeRealm valueRange;
  late _RatioRealm valueRatio;
  late _SampledDataRealm valueSampledData;
  late _FhirTimeRealm valueTime;
  late _PrimitiveElementRealm valueTimeElement;
  late String valueDateTime;
  late _PrimitiveElementRealm valueDateTimeElement;
  late _PeriodRealm valuePeriod;
  late _CodeableConceptRealm dataAbsentReason;
  late List<_CodeableConceptRealm> interpretation;
  late List<_ObservationReferenceRangeRealm> referenceRange;
}
