import 'base64binary_test.dart';
import 'boolean_test.dart';
import 'canonical_test.dart';
import 'code_test.dart';
import 'date_test.dart';
import 'date_time_test.dart';
import 'decimal_test.dart';
import 'id_test.dart';
import 'instant_test.dart';
import 'integer64_test.dart';
import 'integer_test.dart';
import 'markdown_test.dart';
import 'oid_test.dart';
import 'positive_int_test.dart';
import 'string_test.dart';
import 'time_test.dart';
import 'unsigned_int_test.dart';
import 'uri_test.dart';
import 'url_test.dart';
import 'uuid_test.dart';
import 'xhtml_test.dart';

void main() {
  base64BinaryTest();
  booleanTest();
  canonicalTest();
  codeTest();
  dateTest();
  dateTimeTest();
  decimalTest();
  idTest();
  instantTest();
  integerTest();
  integer64Test();
  markdownTest();
  oidTest();
  positiveIntTest();
  stringTest();
  timeTest();
  unsignedIntTest();
  uriTest();
  urlTest();
  uuidTest();
  xhtmlTest();
}
