name: fhir_r4_cql
description: Attempt to Support the CQL Library in Dart.
version: 0.0.0-dev1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/cql

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  antlr4: ^4.13.2
  collection: ^1.19.0
  # fhir_r4: ^0.4.2
  fhir_r4:
    path: ../fhir_r4
  # fhir_r4_path: ^0.4.3
  fhir_r4_path:
    path: ../fhir_r4_path
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.1
  ucum: ^0.6.0
  uuid: ^4.5.1
  xml: ^6.5.0
  xml2json: ^6.2.7
  xml_serializable: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - cql/
    - json/

dependency_overrides:
  meta: ^1.12.0