import 'after_test.dart';
import 'before_test.dart';
import 'collapse_test.dart';
import 'contains_test.dart';
import 'difference_between_test.dart';
import 'duration_between_test.dart';
import 'ends_test.dart';
import 'ends_with_test.dart';
import 'equivalent_test.dart';
import 'expand_test.dart';
import 'greater_or_equal_test.dart';
import 'greater_test.dart';
import 'in_test.dart';
import 'included_in_test.dart';
import 'includes_test.dart';
import 'less_or_equal_test.dart';
import 'less_test.dart';
import 'matches_test.dart';
import 'meets_after_test.dart';
import 'meets_before_test.dart';
import 'meets_test.dart';
import 'overlaps_after_test.dart';
import 'overlaps_before_test.dart';
import 'overlaps_test.dart';
import 'same_as_test.dart';
import 'same_or_after_test.dart';
import 'same_or_before_test.dart';
import 'skip_test.dart';
import 'starts_test.dart';
import 'starts_with_test.dart';
import 'take_test.dart';

void binaryExpressions() {
  afterTest();
  beforeTest();
  collapseTest();
  containsTest();
  differenceBetweenTest();
  durationBetweenTest();
  endsTest();
  endsWithTest();
  equivalentTest();
  expandTest();
  greaterOrEqualTest();
  greaterTest();
  inTest();
  includedInTest();
  includesTest();
  lessOrEqualTest();
  lessTest();
  matchesTest();
  meetsAfterTest();
  meetsBeforeTest();
  meetsTest();
  overlapsAfterTest();
  overlapsBeforeTest();
  overlapsTest();
  sameAsTest();
  sameOrAfterTest();
  sameOrBeforeTest();
  skipTest();
  startsTest();
  startsWithTest();
  takeTest();
}
