import 'package:realm/realm.dart';
@RealmModel()
class _ActivityDefinitionRealm {
  late _R4ResourceTypeRealm resourceType;
  @PrimaryKey() late String id;
  late _FhirMetaRealm meta;
  late _FhirUriRealm implicitRules;
  late _PrimitiveElementRealm implicitRulesElement;
  late _FhirCodeRealm language;
  late _PrimitiveElementRealm languageElement;
  late _NarrativeRealm text;
  late List<_ResourceRealm> contained;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late _FhirUriRealm url;
  late _PrimitiveElementRealm urlElement;
  late List<_IdentifierRealm> identifier;
  late String version;
  late _PrimitiveElementRealm versionElement;
  late String name;
  late _PrimitiveElementRealm nameElement;
  late String title;
  late _PrimitiveElementRealm titleElement;
  late String subtitle;
  late _PrimitiveElementRealm subtitleElement;
  late _FhirCodeRealm status;
  late _PrimitiveElementRealm statusElement;
  late _FhirBooleanRealm experimental;
  late _PrimitiveElementRealm experimentalElement;
  late _CodeableConceptRealm subjectCodeableConcept;
  late _ReferenceRealm subjectReference;
  late _FhirCanonicalRealm subjectCanonical;
  late _PrimitiveElementRealm subjectCanonicalElement;
  late String date;
  late _PrimitiveElementRealm dateElement;
  late String publisher;
  late _PrimitiveElementRealm publisherElement;
  late List<_ContactDetailRealm> contact;
  late _FhirMarkdownRealm description;
  late _PrimitiveElementRealm descriptionElement;
  late List<_UsageContextRealm> useContext;
  late List<_CodeableConceptRealm> jurisdiction;
  late _FhirMarkdownRealm purpose;
  late _PrimitiveElementRealm purposeElement;
  late String usage;
  late _PrimitiveElementRealm usageElement;
  late _FhirMarkdownRealm copyright;
  late _PrimitiveElementRealm copyrightElement;
  late _FhirDateRealm approvalDate;
  late _PrimitiveElementRealm approvalDateElement;
  late _FhirDateRealm lastReviewDate;
  late _PrimitiveElementRealm lastReviewDateElement;
  late _PeriodRealm effectivePeriod;
  late List<_CodeableConceptRealm> topic;
  late List<_ContactDetailRealm> author;
  late List<_ContactDetailRealm> editor;
  late List<_ContactDetailRealm> reviewer;
  late List<_ContactDetailRealm> endorser;
  late List<_RelatedArtifactRealm> relatedArtifact;
  late List<_FhirCanonicalRealm> library_;
  late _FhirCodeRealm kind;
  late _PrimitiveElementRealm kindElement;
  late _FhirCanonicalRealm profile;
  late _CodeableConceptRealm code;
  late _FhirCodeRealm intent;
  late _PrimitiveElementRealm intentElement;
  late _FhirCodeRealm priority;
  late _PrimitiveElementRealm priorityElement;
  late _FhirBooleanRealm doNotPerform;
  late _PrimitiveElementRealm doNotPerformElement;
  late _TimingRealm timingTiming;
  late String timingDateTime;
  late _PrimitiveElementRealm timingDateTimeElement;
  late _AgeRealm timingAge;
  late _PeriodRealm timingPeriod;
  late _RangeRealm timingRange;
  late _FhirDurationRealm timingDuration;
  late _ReferenceRealm location;
  late List<_ActivityDefinitionParticipantRealm> participant;
  late _ReferenceRealm productReference;
  late _CodeableConceptRealm productCodeableConcept;
  late _QuantityRealm quantity;
  late List<_DosageRealm> dosage;
  late List<_CodeableConceptRealm> bodySite;
  late List<_ReferenceRealm> specimenRequirement;
  late List<_ReferenceRealm> observationRequirement;
  late List<_ReferenceRealm> observationResultRequirement;
  late _FhirCanonicalRealm transform;
  late List<_ActivityDefinitionDynamicValueRealm> dynamicValue;
}
@RealmModel()
class _ActivityDefinitionParticipantRealm {
  @PrimaryKey() late String id;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late _FhirCodeRealm type;
  late _PrimitiveElementRealm typeElement;
  late _CodeableConceptRealm role;
}
@RealmModel()
class _ActivityDefinitionDynamicValueRealm {
  @PrimaryKey() late String id;
  late List<_FhirExtensionRealm> extension_;
  late List<_FhirExtensionRealm> modifierExtension;
  late String path;
  late _PrimitiveElementRealm pathElement;
  late _FhirExpressionRealm expression;
}
