name: fhir_r4_utils
description: Utility Library that Peforms Validation and Mapping Functionality.
version: 0.3.0-2
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r4

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0
  crypto: ^3.0.6
  fhir_r4: 
    path: ../fhir_r4
  fhir_r4_path:
    path: ../fhir_r4_path
  http: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.15
