import 'package:fhir_primitives/fhir_primitives.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../r4.dart';
/// [Account_Balance] A financial tool for tracking value accrued for a
/// particular purpose.  In the healthcare field, used to track charges for a
/// patient, cost centers, etc.

@freezed
class Account_Balance with _$Account_Balance {
  const Account_Balance._();

  const factory Account_Balance({
/// [id] Unique id for the element within a resource (for internal
/// references). This may be any string value that does not contain spaces.

    @JsonKey(name: 'id') String? id,
/// [extension] May be used to represent additional information that is not
/// part of the basic definition of the element. To make the use of extensions
/// safe and managable, there is a strict set of governance applied to the
/// definition and use of extensions. Though any implementer can define an
/// extension, there is a set of requirements that SHALL be met as part of the
/// definition of the extension.

    @JsonKey(name: 'extension') List<List<FhirExtension>>? extension,
/// [modifierExtension] May be used to represent additional information
/// that is not part of the basic definition of the element and that modifies
/// the understanding of the element in which it is contained and/or the
/// understanding of the containing element's descendants. Usually modifier
/// elements provide negation or qualification. To make the use of extensions
/// safe and managable, there is a strict set of governance applied to the
/// definition and use of extensions. Though any implementer can define an
/// extension, there is a set of requirements that SHALL be met as part of the
/// definition of the extension. Applications processing a resource are
/// required to check for modifier extensions.
///
/// Modifier extensions SHALL NOT change the meaning of any elements on
/// Resource or DomainResource (including cannot change the meaning of
/// modifierExtension itself).

    @JsonKey(name: 'modifierExtension') List<List<FhirExtension>>? modifierExtension,
/// [aggregate] Who is expected to pay this part of the balance.

    @JsonKey(name: 'aggregate') CodeableConcept? aggregate,
/// [term] The term of the account balances - The balance value is the
/// amount that was outstanding for this age.

    @JsonKey(name: 'term') CodeableConcept? term,
/// [estimate] The amount is only an estimated value - this is likely
/// common for `current` term balances, but not with known terms (that were
/// generated by a backend process).

    @JsonKey(name: 'estimate') FhirBoolean? estimate,
/// [_estimate] Extensions for estimate

    @JsonKey(name: '_estimate') PrimitiveElement? estimateElement,
/// [amount] The actual balance value calculated for the age defined in the
/// term property.

    @JsonKey(name: 'amount') Money? amount,
  }) = _$Account_Balance;

  @override
  String get fhirType => 'Account_Balance';

  factory Account_Balance.fromJson(Map<String, dynamic> json) =>
      _$Account_BalanceFromJson(json);

  factory Account_Balance.fromYaml(dynamic yaml) => yaml is String
      ? Account_Balance.fromJson(
          jsonDecode(jsonEncode(loadYaml(yaml))) as Map<String, dynamic>)
      : yaml is YamlMap
          ? Account_Balance.fromJson(jsonDecode(jsonEncode(yaml)) as Map<String, dynamic>)
          : throw ArgumentError(
              'Account_Balance cannot be constructed from input provided,'
              ' it is neither a yaml string nor a yaml map.');

  factory Account_Balance.fromJsonString(String source) {
    final dynamic json = jsonDecode(source);
    if (json is Map<String, dynamic>) {
      return _$Account_BalanceFromJson(json);
    } else {
      throw FormatException('FormatException:\nYou passed $json\n'
          'This does not properly decode to a Map<String,dynamic>.');
    }
  }
  @override
  String toJsonString() => jsonEncode(toJson());
}
